---
images:
- name: linuxserver/tautulli
  newName: lscr.io/linuxserver/tautulli
  newTag: version-v2.17.1@sha256:8e1a0d8104422f646c3e89d9b261b0507dc664bd6764baaea0ff0a5718f83b94
labels:
- pairs:
    "app.kubernetes.io/name": tautulli
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
