---
images:
- name: linuxserver/tautulli
  newName: lscr.io/linuxserver/tautulli
  newTag: version-v2.18.2@sha256:d3c53deb09f6b8fffd1476c7154da538394193955d1e909f3b126068102fb7cf
labels:
- pairs:
    "app.kubernetes.io/name": tautulli
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
