---
images:
- name: linuxserver/tautulli
  newName: lscr.io/linuxserver/tautulli
  newTag: version-v2.17.0@sha256:8a5fa2a6c585abc64c4ca5423c4a272257363444ed36882ac84ecb6b455da7f0
labels:
- pairs:
    "app.kubernetes.io/name": tautulli
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
