---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-config
  namespace: home-network
data:
  PAPERLESS_TIME_ZONE: "Asia/Kuala_Lumpur"
  PAPERLESS_OCR_LANGUAGE: "eng+msa+chi_sim"
  PAPERLESS_OCR_LANGUAGES: "msa chi_sim"
  PAPERLESS_URL: "https://paperless.services.home.yrf.me"
  # User mapping
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
  # OIDC Configuration (Example values)
  PAPERLESS_ENABLE_ALLAUTH: "true"
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  # Optional OIDC settings
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
  # PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
