---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: home-network
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-ngx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-ngx
        preset-egress-policy: internet-only
    spec:
      restartPolicy: Always
      runtimeClassName: kata
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      automountServiceAccountToken: false
      initContainers:
      - name: broker
        image: docker.io/library/redis:8
        restartPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: redisdata
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      containers:
      - name: gotenberg
        image: docker.io/gotenberg/gotenberg:8.25
        command:
        - "gotenberg"
        - "--chromium-disable-javascript=true"
        - "--chromium-allow-list=file:///tmp/.*"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: tika
        image: docker.io/apache/tika:latest
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /tika
            port: 9998
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /tika
            port: 9998
          initialDelaySeconds: 10
          periodSeconds: 10
      - name: webserver
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: paperless-ngx-config
        - secretRef:
            name: paperless-ngx-secrets
        env:
        - name: PAPERLESS_REDIS
          value: redis://localhost:6379
        - name: PAPERLESS_DBHOST
          valueFrom:
            secretKeyRef:
              name: rfhome-postgres-ha-pguser-paperless-ngx
              key: host
        - name: PAPERLESS_DBPORT
          valueFrom:
            secretKeyRef:
              name: rfhome-postgres-ha-pguser-paperless-ngx
              key: port
        - name: PAPERLESS_DBNAME
          valueFrom:
            secretKeyRef:
              name: rfhome-postgres-ha-pguser-paperless-ngx
              key: dbname
        - name: PAPERLESS_DBUSER
          valueFrom:
            secretKeyRef:
              name: rfhome-postgres-ha-pguser-paperless-ngx
              key: user
        - name: PAPERLESS_DBPASS
          valueFrom:
            secretKeyRef:
              name: rfhome-postgres-ha-pguser-paperless-ngx
              key: password
        - name: PAPERLESS_DBSSLMODE
          value: "require"
        - name: PAPERLESS_TIKA_ENABLED
          value: "1"
        - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
          value: http://localhost:3000
        - name: PAPERLESS_TIKA_ENDPOINT
          value: http://localhost:9998
        volumeMounts:
        - mountPath: /usr/src/paperless/data
          name: data
          subPath: data
        - mountPath: /usr/src/paperless/media
          name: data
          subPath: media
        - mountPath: /tmp/paperless
          name: tmpdir
        # - mountPath: /usr/src/paperless/export
        #   name: data
        #   subPath: export
        # - mountPath: /usr/src/paperless/consume
        #   name: data
        #   subPath: consume
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: '4'
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: paperless-ngx-data
      - name: tmpdir
        emptyDir: {}
