---
images:
- name: docker.io/library/redis
  newTag: 8.8.0@sha256:aa049e689e141a4358ad1d4562dc49c88a89fbab711fd8fcc33f684c80b26301
- name: docker.io/gotenberg/gotenberg
  newTag: 8.34.0@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
- name: docker.io/apache/tika
  newTag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
- name: ghcr.io/paperless-ngx/paperless-ngx
  newTag: 3.0.5@sha256:65a4cabf0169ea7fbd90ab7bb28ba3f8b5909613635acda1a03ad606f34b456b
labels:
- pairs:
    "app.kubernetes.io/name": paperless-ngx
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
- paperless-ngx.sealed.yaml
