---
images:
- name: docker.io/library/redis
  newTag: 8.10.0@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
- name: docker.io/gotenberg/gotenberg
  newTag: 8.34.0@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
- name: docker.io/apache/tika
  newTag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
- name: ghcr.io/paperless-ngx/paperless-ngx
  newTag: 2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
labels:
- pairs:
    "app.kubernetes.io/name": paperless-ngx
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
- paperless-ngx.sealed.yaml
