---
images:
- name: ghcr.io/flaresolverr/flaresolverr
  newName: ghcr.io/flaresolverr/flaresolverr
  newTag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
labels:
- pairs:
    "app.kubernetes.io/name": flaresolverr
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
