---
images:
- name: ghcr.io/flaresolverr/flaresolverr
  newName: ghcr.io/flaresolverr/flaresolverr
  newTag: v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
labels:
- pairs:
    "app.kubernetes.io/name": flaresolverr
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
