// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetRepositoryOwner {
    /**
     * Email address of the user.
     */
    email?: string;
    /**
     * Full name of the user.
     */
    fullName?: string;
    /**
     * Numeric identifier of the user.
     */
    id?: number;
    /**
     * Name of the user.
     */
    login: string;
    /**
     * Login name of the user.
     */
    loginName?: string;
}

export interface GetRepositoryOwnerArgs {
    /**
     * Email address of the user.
     */
    email?: pulumi.Input<string>;
    /**
     * Full name of the user.
     */
    fullName?: pulumi.Input<string>;
    /**
     * Numeric identifier of the user.
     */
    id?: pulumi.Input<number>;
    /**
     * Name of the user.
     */
    login: pulumi.Input<string>;
    /**
     * Login name of the user.
     */
    loginName?: pulumi.Input<string>;
}

export interface RepositoryExternalTracker {
    /**
     * External Issue Tracker URL Format. Use the placeholders `{user}`, `{repo}` and `{index}` for the username, repository name and issue index.
     */
    externalTrackerFormat: pulumi.Input<string>;
    /**
     * External Issue Tracker Number Format.
     */
    externalTrackerStyle?: pulumi.Input<string>;
    /**
     * URL of external issue tracker.
     */
    externalTrackerUrl: pulumi.Input<string>;
}

export interface RepositoryExternalWiki {
    /**
     * URL of external wiki.
     */
    externalWikiUrl: pulumi.Input<string>;
}

export interface RepositoryInternalTracker {
    /**
     * Let only contributors track time?
     */
    allowOnlyContributorsToTrackTime?: pulumi.Input<boolean>;
    /**
     * Enable dependencies for issues and pull requests?
     */
    enableIssueDependencies?: pulumi.Input<boolean>;
    /**
     * Enable time tracking?
     */
    enableTimeTracker?: pulumi.Input<boolean>;
}

export interface RepositoryPermissions {
    /**
     * Allowed to administer?
     */
    admin?: pulumi.Input<boolean>;
    /**
     * Allowed to pull?
     */
    pull?: pulumi.Input<boolean>;
    /**
     * Allowed to push?
     */
    push?: pulumi.Input<boolean>;
}
