---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- networkattachmentdefinition.yaml
- ciliumnetworkpolicy.yaml
- slzb-ultima-wg-secrets.sealed.yaml
