---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: lscr.io/linuxserver/wireguard
  newTag: "1.0.20260223@sha256:2868ae5e3dd9065ea3b1e44b4214b33b02b7ce5ebcb9e4f33e1132b75007f39c"
- name: alpine/socat
  newTag: "1.8.1.3@sha256:d58f04c8555f5d04ffab547566d46725ca397dca71b84a5aabf91669de3f4e09"
resources:
- deployment.yaml
- service.yaml
- networkattachmentdefinition.yaml
- ciliumnetworkpolicy.yaml
- slzb-ultima-wg-secrets.sealed.yaml
- persistentvolumeclaim.yaml
