---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: lscr.io/linuxserver/wireguard
  newTag: "1.0.20260223@sha256:34197b6d2731468a0e77eeb31723af07faf342878be66c1e861e287ec3600b3c"
- name: alpine/socat
  newTag: "1.8.1.3@sha256:d58f04c8555f5d04ffab547566d46725ca397dca71b84a5aabf91669de3f4e09"
resources:
- deployment.yaml
- service.yaml
- networkattachmentdefinition.yaml
- ciliumnetworkpolicy.yaml
- slzb-ultima-wg-secrets.sealed.yaml
