---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slzb-ultima-wg-secrets
  namespace: home-network-privileged
spec:
  encryptedData:
    wg0.conf: AgBhF2rcJN/YpnQrv3KlRw/JpT995GVe83X2Xmt3g+5HqDUG5oGYeBkDWMzbsMBCSDqGbNztsTutC8feuq9uWPYn7iz845fUlQLjcDEBNkwZBeryx45gOdx671Yf8ANXr2Z+vPrkUFFn/hv9Y59tjPRsYvl1Pv0i3SHRO9/E2YmOGo+KjVP7r0DkK8DX/cvSYwLUO86Fk8mUWRk57BTyvaqdQaC8CFkVD8nVMf5TJ7KQHs2e+KDRkB0tLJ41G6Dc7+rGex8Z2PC/6fJKKZrmQ5akJsT7RSrWcreTwek88F7UGsmhUY+3Rb75TmOrAEda2NV2mfAwyfcG3788RmPrnBD3bLLidv/u0qT7KbHGmDu9hiY1qv5X1vdqdAsmrv1XrDW+/sbAfIQILPoYUhfLOsAi6gOuryMkKrIWoobjpiiGQ3qixw/gsdtXMhrgZVSdl0VHJPq4mi/WSrjXyQmSRyZ7S6k1C7EsE4delXh8NovLASXUhZttTrG1qVCp9LlJ1xHi/K22FkC4NltJ/1NfC14kEG36yIOcc23jlzIEnjePA2EANsAwpLxw+odP9jokz4mxTQF14+vlgOsXRY4ASdqNSpPsiL3ILDDjihut/HNwkrN1YUTBn98i0/0ECTQl14FkiW7N+Ytlaz7a8H+L1xX16q+UHhW3IiHtd1QSzg2UXXLbdyYjmHjryicfzVxLLc8+kAuR083FLt0IwYjXA4TSAzyWxPhEjfv9xryE+v1+6xasWOseHobUNp35maeHiJrdxBFzAH6FcuegwPG1K4giGBHiGhmx+Nj3eQm6ioZJtplCp/bsbLB1rZu3DxPK7PQyMFr2+KUw9CmWjlyb7RGngQ8hABweaQ+drijeROtP6JBOtFgDXF4UcUZIg9x3LchNaCos7Jcq3zF9R2/HPgznHlNNL18syAgb9Z4vBiZAZS6mJT95iWh9Srn6Bb43dQ3GSoZDFZ1x7PgRkT8vjKoL51CEQ0RCHbEK6ds+Bj/ms0Mcw6S281zbNQVaL81XMEN3i4VwX3teKVqdn/GOFmm7LZkJTXceR4abtoltu3DI
  template:
    metadata:
      name: slzb-ultima-wg-secrets
      namespace: home-network-privileged
    type: Opaque
