---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: whereabouts-cni-ipam-chart
  namespace: kube-system
spec:
  interval: 24h
  url: oci://harbor.services.home.yrf.me/ghcr/k8snetworkplumbingwg/whereabouts-chart
  ref:
    tag: 0.9.3
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whereabouts-cni-ipam
  namespace: kube-system
spec:
  releaseName: whereabouts-cni-ipam
  chartRef:
    kind: OCIRepository
    name: whereabouts-cni-ipam-chart
  interval: 15m
  timeout: 60m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/whereabouts
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v0.9.3
    priorityClassName: system-cluster-critical
    nodeSliceController:
      enabled: true
      priorityClassName: system-cluster-critical
