---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hamh-secrets
  namespace: home-network
spec:
  encryptedData:
    HAMH_HOME_ASSISTANT_ACCESS_TOKEN: AgC0/qdVkOLispvLNx/ISpn/KjHdrgvpM80tfKSVJwZz1SDH6isAV0Pr+g4gb8IoWpNvjjqk8ayxdLKpciBxseJxPPvQFb+CM2sinaGtOSKDTtwkBLnVNrJ0+UdpCZdwarMWY+FRchNyKK5Ec0fMcDag0yi+lK/GVPrTy8MXnbCpbcEdRIq4YaTQBhzcZ6pwwLzVuEx3JcV8caRb933R+hvI7x3fJoTgcn37iFpcbDPoVOift0+GNned5GXSNJIPV3mFcF6yC0BniVUP0YGjVm71VXYnus2EK3yiFTTFWxOv5mpobmy47QzrQlmtQfn9ikBMp/13vyJAj1zUIdK3Xyysyyt2ocBcHqhHDb3Z5JXzKrHu2HkiCpjtq5MGbYLci1RK/9JiHjfWSPexiou2wxqtgHWjzAu/XakhkF9ZYynaqRzfQ0iXJDtesOK9eyihTQe54dgjvfZEu9xEUlbidIK3NpB5OwK477Y61oZDGII8Lx2Gt7eDiOCkqxgKbw6TxIAYfBtviuR1r4Mtbx/FzPqUY8ZXnaMl7WezqWkzfABUcAyX96r4hDNNoVJFY99Voy8idvy8mo8T0Ql6Q4BIwlCi6S9f812vJlHG6b4nrpnZuusZEItgDjP2tCLfNLC1AHQd60MPZZCji2fAhxnvViMryjyj4T2fB0lCTS8rPknCVKWQjiqAwUmAx70DWf4edkhf6dkpxHEfYmwQeQvRccQQcyZlcRdkRzvdH4c2n0D8x8nCf4O7WHiMlVolmXg+vwH5Z+5uJCWb2S4TXkXf46rhu3+cpsfsOS9XUnWMkmqzb+VAgApr1NUIOPiMvf7MQ6vyFKpAwCMHqKNWk1eWccWG0EcBY+mqa85luhdlgczka4Fs232tl4JHCLcart0uw08NnUNzZOoMqmgxhMXWQ7PV6kQmGEfQTzGHC+UYC7A4Rh+aUuWP0ok=
  template:
    metadata:
      name: hamh-secrets
      namespace: home-network
    type: Opaque
