---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/riddix/home-assistant-matter-hub
  newTag: latest
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- networkattachmentdefinition.yaml
- ciliumnetworkpolicy.yaml
- hamh-secrets.sealed.yaml
patches: []
labels:
- pairs:
    app.kubernetes.io/name: home-assistant-matter-hub
  includeTemplates: true
  includeSelectors: false
