---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/riddix/home-assistant-matter-hub
  newTag: 2.0.58@sha256:3b1aa47b49d6f99dac336633f5a3f3ceed7a340b4e9cd4bdd90fbebd0e32db4e
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- networkattachmentdefinition.yaml
- ciliumnetworkpolicy.yaml
- hamh-secrets.sealed.yaml
patches: []
labels:
- pairs:
    app.kubernetes.io/name: home-assistant-matter-hub
  includeTemplates: true
  includeSelectors: false
