---
images:
- name: ghcr.io/seerr-team/seerr
  newTag: v3.1.1@sha256:d535391db3b5a22ce02241e6d7a50ca714e75d927e46aa20456b77fa051cbf52
labels:
- pairs:
    "app.kubernetes.io/name": overseerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
