---
images:
- name: ghcr.io/seerr-team/seerr
  newTag: v3.1.0
labels:
- pairs:
    "app.kubernetes.io/name": overseerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
