// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCollaborator(args: GetCollaboratorArgs, opts?: pulumi.InvokeOptions): Promise<GetCollaboratorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("forgejo:index/getCollaborator:getCollaborator", {
        "repositoryId": args.repositoryId,
        "user": args.user,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCollaborator.
 */
export interface GetCollaboratorArgs {
    repositoryId: number;
    user: string;
}

/**
 * A collection of values returned by getCollaborator.
 */
export interface GetCollaboratorResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly permission: string;
    readonly repositoryId: number;
    readonly user: string;
}
export function getCollaboratorOutput(args: GetCollaboratorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCollaboratorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("forgejo:index/getCollaborator:getCollaborator", {
        "repositoryId": args.repositoryId,
        "user": args.user,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCollaborator.
 */
export interface GetCollaboratorOutputArgs {
    repositoryId: pulumi.Input<number>;
    user: pulumi.Input<string>;
}
