// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRepository(args: GetRepositoryArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("forgejo:index/getRepository:getRepository", {
        "name": args.name,
        "owner": args.owner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepository.
 */
export interface GetRepositoryArgs {
    name: string;
    owner: inputs.GetRepositoryOwner;
}

/**
 * A collection of values returned by getRepository.
 */
export interface GetRepositoryResult {
    readonly allowMergeCommits: boolean;
    readonly allowRebase: boolean;
    readonly allowRebaseExplicit: boolean;
    readonly allowSquashMerge: boolean;
    readonly archived: boolean;
    readonly avatarUrl: string;
    readonly cloneAddr: string;
    readonly cloneUrl: string;
    readonly createdAt: string;
    readonly defaultBranch: string;
    readonly defaultMergeStyle: string;
    readonly description: string;
    readonly empty: boolean;
    readonly externalTracker: outputs.GetRepositoryExternalTracker;
    readonly externalWiki: outputs.GetRepositoryExternalWiki;
    readonly fork: boolean;
    readonly forksCount: number;
    readonly fullName: string;
    readonly hasActions: boolean;
    readonly hasIssues: boolean;
    readonly hasPackages: boolean;
    readonly hasProjects: boolean;
    readonly hasPullRequests: boolean;
    readonly hasReleases: boolean;
    readonly hasWiki: boolean;
    readonly htmlUrl: string;
    readonly id: number;
    readonly ignoreWhitespaceConflicts: boolean;
    readonly internal: boolean;
    readonly internalTracker: outputs.GetRepositoryInternalTracker;
    readonly mirror: boolean;
    readonly mirrorInterval: string;
    readonly mirrorUpdated: string;
    readonly name: string;
    readonly openIssuesCount: number;
    readonly openPrCounter: number;
    readonly owner: outputs.GetRepositoryOwner;
    readonly parentId: number;
    readonly permissions: outputs.GetRepositoryPermissions;
    readonly private: boolean;
    readonly releaseCounter: number;
    readonly size: number;
    readonly sshUrl: string;
    readonly starsCount: number;
    readonly template: boolean;
    readonly updatedAt: string;
    readonly watchersCount: number;
    readonly website: string;
}
export function getRepositoryOutput(args: GetRepositoryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("forgejo:index/getRepository:getRepository", {
        "name": args.name,
        "owner": args.owner,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRepository.
 */
export interface GetRepositoryOutputArgs {
    name: pulumi.Input<string>;
    owner: pulumi.Input<inputs.GetRepositoryOwnerArgs>;
}
