// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("forgejo:index/getUser:getUser", {
        "login": args.login,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    login: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    readonly active: boolean;
    readonly avatarUrl: string;
    readonly createdAt: string;
    readonly description: string;
    readonly email: string;
    readonly followersCount: number;
    readonly followingCount: number;
    readonly fullName: string;
    readonly htmlUrl: string;
    readonly id: number;
    readonly isAdmin: boolean;
    readonly language: string;
    readonly lastLogin: string;
    readonly location: string;
    readonly login: string;
    readonly loginName: string;
    readonly prohibitLogin: boolean;
    readonly restricted: boolean;
    readonly sourceId: number;
    readonly starredReposCount: number;
    readonly visibility: string;
    readonly website: string;
}
export function getUserOutput(args: GetUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("forgejo:index/getUser:getUser", {
        "login": args.login,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    login: pulumi.Input<string>;
}
