// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("authentik");

/**
 * Optional HTTP headers sent with every request
 */
export declare const headers: {[key: string]: string} | undefined;
Object.defineProperty(exports, "headers", {
    get() {
        return __config.getObject<{[key: string]: string}>("headers");
    },
    enumerable: true,
});

/**
 * Whether to skip TLS verification, can optionally be passed as `AUTHENTIK_INSECURE` environmental variable
 */
export declare const insecure: boolean | undefined;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure");
    },
    enumerable: true,
});

/**
 * The authentik API token, can optionally be passed as `AUTHENTIK_TOKEN` environmental variable
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * The authentik API endpoint, can optionally be passed as `AUTHENTIK_URL` environmental variable
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});
