---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n-chart
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/n8n-io/n8n-helm-chart/n8n
  ref:
    tag: 1.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: home-network
spec:
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: n8n-chart
  interval: 15m
  targetNamespace: home-network
  install:
    disableWait: true
  upgrade:
    disableWait: true
  valuesFrom:
  - kind: Secret
    name: rfhome-postgres-ha-pguser-n8n
    valuesKey: host
    targetPath: database.host
  - kind: Secret
    name: rfhome-postgres-ha-pguser-n8n
    valuesKey: port
    targetPath: database.port
  - kind: Secret
    name: rfhome-postgres-ha-pguser-n8n
    valuesKey: user
    targetPath: database.user
  - kind: Secret
    name: rfhome-postgres-ha-pguser-n8n
    valuesKey: dbname
    targetPath: database.database
  values:
    fullnameOverride: n8n
    image:
      repository: n8nio/n8n
      tag: 2.17.0@sha256:cd1fd0e71945cd492a61f90aab802a188015e62bf560c24d4cf752f03250076a
    secretRefs:
      existingSecret: n8n-secret
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    ingress:
      enabled: false
    database:
      type: postgresdb
      passwordSecret:
        name: rfhome-postgres-ha-pguser-n8n
        key: password
      ssl:
        enabled: true
        ca: /opt/custom-certificates/postgres-ca.crt
        rejectUnauthorized: false
    queueMode:
      enabled: false
    redis:
      host: redis-ha-proxy
      database: 1
      prefix: 'n8n:'
    extraVolumes:
    - name: n8n-hooks
      configMap:
        name: n8n-hooks
    - name: postgres-ca
      secret:
        secretName: rfhome-postgres-ha-cluster-cert
    - name: custom-certs-tmpfs
      emptyDir:
        medium: Memory
    - name: patched-files
      emptyDir:
        medium: Memory
    extraVolumeMounts:
    #    - name: n8n-hooks
    #      mountPath: /home/node/.n8n/hooks.js
    #      subPath: hooks.js
    #      readOnly: true
    - name: custom-certs-tmpfs
      mountPath: /opt/custom-certificates
    - name: postgres-ca
      mountPath: /opt/custom-certificates/postgres-ca.crt
      subPath: ca.crt
    - name: patched-files
      mountPath: /usr/local/lib/node_modules/n8n/dist/license.js
      subPath: license.js
    - name: patched-files
      mountPath: /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+permissions@file+packages+@n8n+permissions/node_modules/@n8n/permissions/dist/roles/scopes/global-scopes.ee.js
      subPath: global-scopes.ee.js
    s3:
      enabled: true
      bucket:
        name: rfhome-n8n
        region: us-east-1
        host: okinawa-s3.services.home.yrf.me
      auth:
        accessKeyId: n8n@home-network.pathweb
        secretAccessKeySecret:
          name: n8n-secret
          key: S3_SECRET_ACCESS_KEY
    strategy:
      type: Recreate
    pdb:
      enabled: false
    taskRunners:
      enabled: true
      image:
        repository: n8nio/runners
        tag: 2.17.0@sha256:e2e8ee440794aaa6be558754eb00919515f05dcb357b623a39ceff5585f24f2a
      authToken:
        existingSecret: n8n-secret
        existingSecretKey: N8N_TASK_RUNNER_AUTH_TOKEN
    persistence:
      enabled: true
      accessModes: ["ReadWriteMany"]
      size: 8Gi
      storageClassName: cephfs
      annotations:
        home.yrf.me/backup-to-okinawa-s3: "true"
    webhook:
      url: https://rfhome-n8n.p.0spkl.dev
    license:
      enabled: true
      existingSecret:
        name: n8n-secret
        key: N8N_LICENSE_KEY
    config:
      timezone: Asia/Kuala_Lumpur
      extraEnv:
      - name: N8N_EDITOR_BASE_URL
        value: https://n8n.services.home.yrf.me
      - name: N8N_SECURE_COOKIE
        value: "true"
      - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - name: N8N_PROXY_HOPS
        value: "2"
      - name: N8N_EMAIL_MODE
        value: smtp
      - name: N8N_SMTP_HOST
        value: smtp.eu.mailgun.org
      - name: N8N_SMTP_PORT
        value: "587"
      - name: N8N_SMTP_USER
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: N8N_SMTP_USER
      - name: N8N_SMTP_SENDER
        value: rfhome-n8n@mg.0spkl.dev
      - name: N8N_SMTP_SSL
        value: "true"
      - name: N8N_SMTP_PASS
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: N8N_SMTP_PASS
      - name: N8N_DIAGNOSTICS_ENABLED
        value: "false"
        #      - name: EXTERNAL_FRONTEND_HOOKS_URLS
        #        value: /assets/oidc-frontend-hook.js
        #      - name: EXTERNAL_HOOK_FILES
        #        value: /home/node/.n8n/hooks.js
        #      - name: N8N_TRUST_PROXY
        #        value: "true"
        #      - name: OIDC_ISSUER_URL
        #        valueFrom:
        #          secretKeyRef:
        #            name: n8n-secret
        #            key: OIDC_ISSUER_URL
        #      - name: OIDC_CLIENT_ID
        #        valueFrom:
        #          secretKeyRef:
        #            name: n8n-secret
        #            key: OIDC_CLIENT_ID
        #      - name: OIDC_CLIENT_SECRET
        #        valueFrom:
        #          secretKeyRef:
        #            name: n8n-secret
        #            key: OIDC_CLIENT_SECRET
        #      - name: OIDC_REDIRECT_URI
        #        value: https://n8n.services.home.yrf.me/auth/oidc/callback
        #      - name: N8N_ADDITIONAL_NON_UI_ROUTES
        #        value: auth
    nodeSelector:
      kubernetes.io/os: linux
      location: rfhome
    priorityClassName: rfhome-standard
  postRenderers:
  - kustomize:
      patches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: n8n-main
        patch: |-
          - op: add
            path: /spec/template/spec/initContainers
            value:
            - name: patch-n8n
              image: n8nio/n8n:2.17.0@sha256:cd1fd0e71945cd492a61f90aab802a188015e62bf560c24d4cf752f03250076a
              command:
              - sh
              - /etc/n8n-scripts/activate-ee.sh
              volumeMounts:
              - name: patched-files
                mountPath: /patched
              - name: n8n-hooks
                mountPath: /etc/n8n-scripts/activate-ee.sh
                subPath: activate-ee.sh
