---
nameReference:
- kind: ConfigMap
  fieldSpecs:
  - kind: HelmRelease
    path: spec/values/extraVolumes/configMap/name
  - kind: HelmRelease
    path: spec/postRenderers/kustomize/patches/patch
- kind: Secret
  fieldSpecs:
  - kind: HelmRelease
    path: spec/values/secretRefs/existingSecret
  - kind: HelmRelease
    path: spec/values/taskRunners/authToken/existingSecret
  - kind: HelmRelease
    path: spec/values/database/passwordSecret/name
  - kind: HelmRelease
    path: spec/values/license/existingSecret/name
