---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- n8n.sealed.yaml
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: n8n-hooks
  files:
  #  - hooks.js
  - activate-ee.sh
labels:
- pairs:
    app.kubernetes.io/name: n8n
  includeTemplates: true
  includeSelectors: false
