---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: home-network-privileged
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
      annotations:
        k8s.v1.cni.cncf.io/networks: otbr-iot-network
    spec:
      runtimeClassName: kata
      nodeSelector:
        kubernetes.io/os: linux
        location: rfhome
      containers:
      - name: otbr
        image: ghcr.io/ownbee/hass-otbr-docker:latest
        command: ["docker-entrypoint.sh"]
        args: ["otbr-agent"]
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        envFrom:
        - configMapRef:
            name: otbr
        resources:
          limits:
            squat.ai/net-tun: 1
          requests:
            squat.ai/net-tun: 1
        volumeMounts:
        - name: otbr-data
          mountPath: /data
        ports:
        - containerPort: 8081
          name: rest
        - containerPort: 8082
          name: web
      volumes:
      - name: otbr-data
        persistentVolumeClaim:
          claimName: otbr-data
