---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: home-network-privileged
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
      annotations:
        k8s.v1.cni.cncf.io/networks: otbr-iot-network
    spec:
      runtimeClassName: kata
      nodeSelector:
        kubernetes.io/os: linux
        location: rfhome
      initContainers:
      - name: init-root
        image: ghcr.io/ownbee/hass-otbr-docker:v0.3.0@sha256:5ca7008462e94d4c937aca8c1c9a60e709d6d300625363c161b946683032d5b1
        command: ["/bin/sh", "-c", "cp -a /etc/s6-overlay/s6-rc.d/otbr-agent/* /otbr-root/"]
        volumeMounts:
        - name: otbr-root
          mountPath: /otbr-root
      - name: patch-rest-listen
        image: busybox
        command: ["/bin/sh", "/scripts/patch-otbr-rest-listen.sh"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: otbr-root
          mountPath: /etc/s6-overlay/s6-rc.d/otbr-agent
      - name: patch-agent
        image: ghcr.io/ownbee/hass-otbr-docker:v0.3.0@sha256:5ca7008462e94d4c937aca8c1c9a60e709d6d300625363c161b946683032d5b1
        command: ["/bin/sh", "/scripts/patch-otbr-agent.sh"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: patched-scripts
          mountPath: /patched
      containers:
      - name: otbr
        image: ghcr.io/ownbee/hass-otbr-docker:latest
        # command: ["docker-entrypoint.sh"]
        # args: ["otbr-agent"]
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: otbr
        resources:
          limits:
            squat.ai/net-tun: 1
          requests:
            squat.ai/net-tun: 1
        volumeMounts:
        - name: otbr-data
          mountPath: /data
        - name: scripts
          mountPath: /scripts
        - name: otbr-root
          mountPath: /etc/s6-overlay/s6-rc.d/otbr-agent
        - name: patched-scripts
          mountPath: /etc/s6-overlay/s6-rc.d/otbr-agent/run
          subPath: run
        ports:
        - containerPort: 8081
          name: rest
        - containerPort: 8082
          name: web
      volumes:
      - name: otbr-data
        persistentVolumeClaim:
          claimName: otbr-data
      - name: scripts
        configMap:
          name: otbr-patch
          defaultMode: 0755
      - name: otbr-root
        emptyDir: {}
      - name: patched-scripts
        emptyDir: {}
