---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- networkattachmentdefinition.yaml
- configmap.yaml
- persistentvolumeclaim.yaml
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
images:
- name: ghcr.io/wittdennis/homeassistant-otbr
  newTag: 4.2.6@sha256:a0c2b5eeb050b415815344c2206a9fde52a0b69bfa1c66527bbaf5ed2bf5d6c3
configMapGenerator:
- name: otbr-patch
  files:
  - patch-otbr-agent.sh
- name: otbr-leader-locker
  files:
  - leader-locker.sh
