---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- networkattachmentdefinition.yaml
- configmap.yaml
- persistentvolumeclaim.yaml
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
images:
- name: ghcr.io/wittdennis/homeassistant-otbr
  newTag: 4.2.7@sha256:df1ba94bd5c0ee3acfd7a288e705a4c3e14c840e94aac5f277b8a19dd9158ed5
configMapGenerator:
- name: otbr-patch
  files:
  - patch-otbr-agent.sh
- name: otbr-leader-locker
  files:
  - leader-locker.sh
