---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: otbr-data
  namespace: home-network
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
