---
images:
- name: ghcr.io/maintainerr/maintainerr
  newTag: 3.20.1@sha256:ce7ff52afa146dfc05c2c2304df8141e0086f14a803bdbef0d870e5b914f0dee
labels:
- pairs:
    "app.kubernetes.io/name": maintainerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
