---
images:
- name: ghcr.io/maintainerr/maintainerr
  newTag: 3.20.0@sha256:049db172a9b98998480e48b4061c51c4b90adfb18158863cb9c8f65f0cfba4f3
labels:
- pairs:
    "app.kubernetes.io/name": maintainerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
