---
images:
- name: ghcr.io/maintainerr/maintainerr
  newTag: 3.10.2@sha256:b6a8c18a1f72d26d0c290bc7002ab766def19eca0f28bc2fa1ab9ae7cd7de06c
labels:
- pairs:
    "app.kubernetes.io/name": maintainerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
