---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik-chart
  namespace: traefik
spec:
  interval: 24h
  url: oci://harbor.services.home.yrf.me/ghcr/traefik/helm/traefik
  ref:
    tag: 40.3.0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
