---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: homeassistant/home-assistant
  newName: ghcr.io/home-assistant/home-assistant
  newTag: "2026.7.2@sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b"
- name: ghcr.io/home-assistant-libs/python-matter-server
  newTag: "8.1.0@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a"
- name: alpine
  newTag: "3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b"
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- backup-credentials.sealed.yaml
- hass-secrets.sealed.yaml
patches: []
configMapGenerator:
- name: homeassistant-docker-venv
  files:
  - venv-run
  - leader-locker.sh
  - matter-server.sh
  - ha-probe.sh
labels:
- pairs:
    app.kubernetes.io/version: 2026.4.2
  includeTemplates: true
  includeSelectors: false
