---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: homeassistant/home-assistant
  newName: ghcr.io/home-assistant/home-assistant
  newTag: "2026.9.3@sha256:d8922685169707fd91e8b9729902d975f06157d005e422874d201e0261dda196"
- name: ghcr.io/matter-js/matterjs-server
  newTag: "1.4.0@sha256:54232d0d3e7dff5a54759469d2753399270412b4c30c55b31750a4595e4cb236"
- name: alpine
  newTag: "3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6"
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- backup-credentials.sealed.yaml
- hass-secrets.sealed.yaml
patches: []
configMapGenerator:
- name: homeassistant-docker-venv
  files:
  - venv-run
  - leader-locker.sh
  - matter-server.sh
  - ha-probe.sh
  - sync-http-settings.py
- name: ha-config-extra
  files:
  - ha-http-config.yaml
  - hass-ingress.yaml
labels:
- pairs:
    app.kubernetes.io/version: 2026.4.2
  includeTemplates: true
  includeSelectors: false
