---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: homeassistant/home-assistant
  newName: ghcr.io/home-assistant/home-assistant
  newTag: "2026.8.0@sha256:a21689ef0510df9760ee11bab4d6b2fef3ed5c1a29ed9c3224271597a23729eb"
- name: ghcr.io/matter-js/matterjs-server
  newTag: "1.3.3@sha256:ac537ba44a2edaaf785b818f8b7ce75cdf736539401462046f0042670bee4063"
- name: alpine
  newTag: "3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b"
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- backup-credentials.sealed.yaml
- hass-secrets.sealed.yaml
patches: []
configMapGenerator:
- name: homeassistant-docker-venv
  files:
  - venv-run
  - leader-locker.sh
  - matter-server.sh
  - ha-probe.sh
labels:
- pairs:
    app.kubernetes.io/version: 2026.4.2
  includeTemplates: true
  includeSelectors: false
