// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMxRecordSet(args: GetMxRecordSetArgs, opts?: pulumi.InvokeOptions): Promise<GetMxRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dns:index/getMxRecordSet:getMxRecordSet", {
        "domain": args.domain,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMxRecordSet.
 */
export interface GetMxRecordSetArgs {
    domain: string;
}

/**
 * A collection of values returned by getMxRecordSet.
 */
export interface GetMxRecordSetResult {
    readonly domain: string;
    readonly id: string;
    readonly mxes: outputs.GetMxRecordSetMx[];
}
export function getMxRecordSetOutput(args: GetMxRecordSetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMxRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dns:index/getMxRecordSet:getMxRecordSet", {
        "domain": args.domain,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMxRecordSet.
 */
export interface GetMxRecordSetOutputArgs {
    domain: pulumi.Input<string>;
}
