// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNsRecordSet(args: GetNsRecordSetArgs, opts?: pulumi.InvokeOptions): Promise<GetNsRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dns:index/getNsRecordSet:getNsRecordSet", {
        "host": args.host,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNsRecordSet.
 */
export interface GetNsRecordSetArgs {
    host: string;
}

/**
 * A collection of values returned by getNsRecordSet.
 */
export interface GetNsRecordSetResult {
    readonly host: string;
    readonly id: string;
    readonly nameservers: string[];
}
export function getNsRecordSetOutput(args: GetNsRecordSetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNsRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dns:index/getNsRecordSet:getNsRecordSet", {
        "host": args.host,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNsRecordSet.
 */
export interface GetNsRecordSetOutputArgs {
    host: pulumi.Input<string>;
}
