// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTxtRecordSet(args: GetTxtRecordSetArgs, opts?: pulumi.InvokeOptions): Promise<GetTxtRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dns:index/getTxtRecordSet:getTxtRecordSet", {
        "host": args.host,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTxtRecordSet.
 */
export interface GetTxtRecordSetArgs {
    host: string;
}

/**
 * A collection of values returned by getTxtRecordSet.
 */
export interface GetTxtRecordSetResult {
    readonly host: string;
    readonly id: string;
    readonly record: string;
    readonly records: string[];
}
export function getTxtRecordSetOutput(args: GetTxtRecordSetOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTxtRecordSetResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dns:index/getTxtRecordSet:getTxtRecordSet", {
        "host": args.host,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTxtRecordSet.
 */
export interface GetTxtRecordSetOutputArgs {
    host: pulumi.Input<string>;
}
