// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SrvRecordSet extends pulumi.CustomResource {
    /**
     * Get an existing SrvRecordSet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SrvRecordSetState, opts?: pulumi.CustomResourceOptions): SrvRecordSet {
        return new SrvRecordSet(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dns:index/srvRecordSet:SrvRecordSet';

    /**
     * Returns true if the given object is an instance of SrvRecordSet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SrvRecordSet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SrvRecordSet.__pulumiType;
    }

    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Can be specified multiple times for each SRV record.
     */
    declare public readonly srvs: pulumi.Output<outputs.SrvRecordSetSrv[] | undefined>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    declare public readonly ttl: pulumi.Output<number>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    declare public readonly zone: pulumi.Output<string>;

    /**
     * Create a SrvRecordSet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SrvRecordSetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SrvRecordSetArgs | SrvRecordSetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SrvRecordSetState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["srvs"] = state?.srvs;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as SrvRecordSetArgs | undefined;
            if (args?.zone === undefined && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["srvs"] = args?.srvs;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["zone"] = args?.zone;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SrvRecordSet.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SrvRecordSet resources.
 */
export interface SrvRecordSetState {
    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    name?: pulumi.Input<string>;
    /**
     * Can be specified multiple times for each SRV record.
     */
    srvs?: pulumi.Input<pulumi.Input<inputs.SrvRecordSetSrv>[]>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    ttl?: pulumi.Input<number>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SrvRecordSet resource.
 */
export interface SrvRecordSetArgs {
    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    name?: pulumi.Input<string>;
    /**
     * Can be specified multiple times for each SRV record.
     */
    srvs?: pulumi.Input<pulumi.Input<inputs.SrvRecordSetSrv>[]>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    ttl?: pulumi.Input<number>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    zone: pulumi.Input<string>;
}
