// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TxtRecordSet extends pulumi.CustomResource {
    /**
     * Get an existing TxtRecordSet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TxtRecordSetState, opts?: pulumi.CustomResourceOptions): TxtRecordSet {
        return new TxtRecordSet(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dns:index/txtRecordSet:TxtRecordSet';

    /**
     * Returns true if the given object is an instance of TxtRecordSet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TxtRecordSet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TxtRecordSet.__pulumiType;
    }

    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    declare public readonly ttl: pulumi.Output<number>;
    /**
     * The text records this record set will be set to.
     */
    declare public readonly txts: pulumi.Output<string[]>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    declare public readonly zone: pulumi.Output<string>;

    /**
     * Create a TxtRecordSet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TxtRecordSetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TxtRecordSetArgs | TxtRecordSetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TxtRecordSetState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["txts"] = state?.txts;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as TxtRecordSetArgs | undefined;
            if (args?.txts === undefined && !opts.urn) {
                throw new Error("Missing required property 'txts'");
            }
            if (args?.zone === undefined && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["txts"] = args?.txts;
            resourceInputs["zone"] = args?.zone;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TxtRecordSet.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering TxtRecordSet resources.
 */
export interface TxtRecordSetState {
    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    name?: pulumi.Input<string>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The text records this record set will be set to.
     */
    txts?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TxtRecordSet resource.
 */
export interface TxtRecordSetArgs {
    /**
     * The name of the record set. The <span pulumi-lang-nodejs="`zone`" pulumi-lang-dotnet="`Zone`" pulumi-lang-go="`zone`" pulumi-lang-python="`zone`" pulumi-lang-yaml="`zone`" pulumi-lang-java="`zone`">`zone`</span> argument will be appended to this value to create the full record path.
     */
    name?: pulumi.Input<string>;
    /**
     * The TTL of the record set. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`">`3600`</span>.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The text records this record set will be set to.
     */
    txts: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     */
    zone: pulumi.Input<string>;
}
