---
images:
- name: hotio/unpackerr
  newName: ghcr.io/hotio/unpackerr
  newTag: release-0.15.2@sha256:724c702e81727e3d90c42cf2b3d900674203906a6d135ba07416c9a3f9f67fbb
labels:
- pairs:
    "app.kubernetes.io/name": unpackerr
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
- unpackerr-secrets.sealed.yaml
