---
images:
- name: hotio/unpackerr
  newName: ghcr.io/hotio/unpackerr
  newTag: release-0.15.2@sha256:5d5e36d98630f891ba16649dee59bc9b4ca76d1e4d80e1ffb4fb62bb9f657d34
labels:
- pairs:
    "app.kubernetes.io/name": unpackerr
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
- unpackerr-secrets.sealed.yaml
