---
images:
- name: hotio/unpackerr
  newName: ghcr.io/hotio/unpackerr
  newTag: release-0.15.2@sha256:b0939e1b2c64499b82678a8c8c3e189d1e92c8223633fd34239174382de8ca8a
labels:
- pairs:
    "app.kubernetes.io/name": unpackerr
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
- unpackerr-secrets.sealed.yaml
