---
images:
- name: linuxserver/grocy
  newName: lscr.io/linuxserver/grocy
  newTag: version-v4.7.1@sha256:3c1ce96cb2d0f0c7ea0c2e0b89f5769be7f2f102204fbeef87aeef56afd6036e
labels:
- pairs:
    "app.kubernetes.io/name": grocy
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
