---
images:
- name: linuxserver/grocy
  newName: lscr.io/linuxserver/grocy
  newTag: version-v4.6.0@sha256:e84bfdb1de28a664e6f7b38f78551bd17a3e3ade4fdb0b9f6da4b0fbb306a7a8
labels:
- pairs:
    "app.kubernetes.io/name": grocy
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
