---
images:
- name: linuxserver/grocy
  newName: lscr.io/linuxserver/grocy
  newTag: version-v4.6.0@sha256:a0890ba405a7f7b6eedf9eea756ab0bdb1fb38a06ab77d4c9ccd9418f468bbf5
labels:
- pairs:
    "app.kubernetes.io/name": grocy
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- configmap.yaml
