---
images:
- name: rhasspy/wyoming-whisper
  newTag: 3.4.1@sha256:9f35594df729b2c1d3fa9a69d1faf4432082ed6dab2ba87da1d5a58f4e4e8f52
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
