---
images:
- name: rhasspy/wyoming-whisper
  newTag: 3.5.0@sha256:308b7959a925d0cca381c3e6e77292fed87822695635db39c24199d6b7a9e610
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
