---
commonLabels:
  app.kubernetes.io/part-of: calibre-web
images:
- name: driveone/onedrive
  newTag: "2.5-debian@sha256:0387a11b16169da037be0defd6bcd26f6a42161a596b708875698de568ba6fda"
- name: lscr.io/linuxserver/calibre-web
  newName: ghcr.io/ruifung/lsio-calibre-web-mod
  newTag: "0.6.26-calibre-v9.9.0@sha256:6e69e716b6eeb9c6c05794fda836f61f63edbca6f9abd4b67e63eea315a02613"
resources:
- "calibre-library-pvc.yaml"
- "calibre-web-sts.yaml"
- "calibre-web-svc.yaml"
- "calibre-library-sync-sts.yaml"
- "calibre-library-sync-svc.yaml"
- "traefik-middleware.yaml"
- "traefik-service.yaml"
- "httproute.yaml"
- "httproute-external.yaml"
configMapGenerator:
- name: "calibre-library-sync-config"
  files:
  - "onedrive-config"
