---
commonLabels:
  app.kubernetes.io/part-of: calibre-web
images:
- name: driveone/onedrive
  newTag: "2.5-debian@sha256:0387a11b16169da037be0defd6bcd26f6a42161a596b708875698de568ba6fda"
- name: lscr.io/linuxserver/calibre-web
  newName: ghcr.io/ruifung/lsio-calibre-web-mod
  newTag: "0.6.26-calibre-v9.12.0@sha256:72aa308e0a0b7e86fd88df1485c95975f0b011ea5e44e046d7d5ec0db0fb4d5c"
resources:
- "calibre-library-pvc.yaml"
- "calibre-web-sts.yaml"
- "calibre-web-svc.yaml"
- "calibre-library-sync-sts.yaml"
- "calibre-library-sync-svc.yaml"
- "traefik-middleware.yaml"
- "traefik-service.yaml"
- "httproute.yaml"
- "httproute-external.yaml"
configMapGenerator:
- name: "calibre-library-sync-config"
  files:
  - "onedrive-config"
