// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("dns");

/**
 * When the provider is used for DNS updates, this block is required. Only one <span pulumi-lang-nodejs="`update`" pulumi-lang-dotnet="`Update`" pulumi-lang-go="`update`" pulumi-lang-python="`update`" pulumi-lang-yaml="`update`" pulumi-lang-java="`update`">`update`</span> block may be in the configuration.
 */
export declare const updates: outputs.config.Updates[] | undefined;
Object.defineProperty(exports, "updates", {
    get() {
        return __config.getObject<outputs.config.Updates[]>("updates");
    },
    enumerable: true,
});
