---
images:
- name: plexinc/pms-docker
  newTag: 1.43.3.10861-07dfddaeb@sha256:5bc1d13f48da6366f46aaf2a3ce1a6292897eadc1f8efcbbd7321d30e94f2ed4
resources:
- statefulset.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- httproute.yaml
