---
images:
- name: plexinc/pms-docker
  newTag: 1.43.3.10896-cb3ebc72d@sha256:83a425ae9e133b1cb2cc3b809556e01c61cd8ff65c582e41b4374bc2210bac9e
resources:
- statefulset.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- httproute.yaml
