// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApplicationEntitlement extends pulumi.CustomResource {
    /**
     * Get an existing ApplicationEntitlement resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationEntitlementState, opts?: pulumi.CustomResourceOptions): ApplicationEntitlement {
        return new ApplicationEntitlement(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/applicationEntitlement:ApplicationEntitlement';

    /**
     * Returns true if the given object is an instance of ApplicationEntitlement.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApplicationEntitlement {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApplicationEntitlement.__pulumiType;
    }

    declare public readonly application: pulumi.Output<string>;
    declare public readonly applicationEntitlementId: pulumi.Output<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    declare public readonly attributes: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a ApplicationEntitlement resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationEntitlementArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationEntitlementArgs | ApplicationEntitlementState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationEntitlementState | undefined;
            resourceInputs["application"] = state?.application;
            resourceInputs["applicationEntitlementId"] = state?.applicationEntitlementId;
            resourceInputs["attributes"] = state?.attributes;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as ApplicationEntitlementArgs | undefined;
            if (args?.application === undefined && !opts.urn) {
                throw new Error("Missing required property 'application'");
            }
            resourceInputs["application"] = args?.application;
            resourceInputs["applicationEntitlementId"] = args?.applicationEntitlementId;
            resourceInputs["attributes"] = args?.attributes;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApplicationEntitlement.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ApplicationEntitlement resources.
 */
export interface ApplicationEntitlementState {
    application?: pulumi.Input<string>;
    applicationEntitlementId?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    attributes?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ApplicationEntitlement resource.
 */
export interface ApplicationEntitlementArgs {
    application: pulumi.Input<string>;
    applicationEntitlementId?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    attributes?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
