// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PolicyPassword extends pulumi.CustomResource {
    /**
     * Get an existing PolicyPassword resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyPasswordState, opts?: pulumi.CustomResourceOptions): PolicyPassword {
        return new PolicyPassword(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/policyPassword:PolicyPassword';

    /**
     * Returns true if the given object is an instance of PolicyPassword.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyPassword {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyPassword.__pulumiType;
    }

    declare public readonly amountDigits: pulumi.Output<number | undefined>;
    declare public readonly amountLowercase: pulumi.Output<number | undefined>;
    declare public readonly amountSymbols: pulumi.Output<number | undefined>;
    declare public readonly amountUppercase: pulumi.Output<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly checkHaveIBeenPwned: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly checkStaticRules: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly checkZxcvbn: pulumi.Output<boolean | undefined>;
    declare public readonly errorMessage: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly executionLogging: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`">`1`</span>.
     */
    declare public readonly hibpAllowedCount: pulumi.Output<number | undefined>;
    declare public readonly lengthMin: pulumi.Output<number | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`">`password`</span>.
     */
    declare public readonly passwordField: pulumi.Output<string | undefined>;
    declare public readonly policyPasswordId: pulumi.Output<string>;
    /**
     * Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
     */
    declare public readonly symbolCharset: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`">`2`</span>.
     */
    declare public readonly zxcvbnScoreThreshold: pulumi.Output<number | undefined>;

    /**
     * Create a PolicyPassword resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyPasswordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyPasswordArgs | PolicyPasswordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyPasswordState | undefined;
            resourceInputs["amountDigits"] = state?.amountDigits;
            resourceInputs["amountLowercase"] = state?.amountLowercase;
            resourceInputs["amountSymbols"] = state?.amountSymbols;
            resourceInputs["amountUppercase"] = state?.amountUppercase;
            resourceInputs["checkHaveIBeenPwned"] = state?.checkHaveIBeenPwned;
            resourceInputs["checkStaticRules"] = state?.checkStaticRules;
            resourceInputs["checkZxcvbn"] = state?.checkZxcvbn;
            resourceInputs["errorMessage"] = state?.errorMessage;
            resourceInputs["executionLogging"] = state?.executionLogging;
            resourceInputs["hibpAllowedCount"] = state?.hibpAllowedCount;
            resourceInputs["lengthMin"] = state?.lengthMin;
            resourceInputs["name"] = state?.name;
            resourceInputs["passwordField"] = state?.passwordField;
            resourceInputs["policyPasswordId"] = state?.policyPasswordId;
            resourceInputs["symbolCharset"] = state?.symbolCharset;
            resourceInputs["zxcvbnScoreThreshold"] = state?.zxcvbnScoreThreshold;
        } else {
            const args = argsOrState as PolicyPasswordArgs | undefined;
            if (args?.errorMessage === undefined && !opts.urn) {
                throw new Error("Missing required property 'errorMessage'");
            }
            resourceInputs["amountDigits"] = args?.amountDigits;
            resourceInputs["amountLowercase"] = args?.amountLowercase;
            resourceInputs["amountSymbols"] = args?.amountSymbols;
            resourceInputs["amountUppercase"] = args?.amountUppercase;
            resourceInputs["checkHaveIBeenPwned"] = args?.checkHaveIBeenPwned;
            resourceInputs["checkStaticRules"] = args?.checkStaticRules;
            resourceInputs["checkZxcvbn"] = args?.checkZxcvbn;
            resourceInputs["errorMessage"] = args?.errorMessage;
            resourceInputs["executionLogging"] = args?.executionLogging;
            resourceInputs["hibpAllowedCount"] = args?.hibpAllowedCount;
            resourceInputs["lengthMin"] = args?.lengthMin;
            resourceInputs["name"] = args?.name;
            resourceInputs["passwordField"] = args?.passwordField;
            resourceInputs["policyPasswordId"] = args?.policyPasswordId;
            resourceInputs["symbolCharset"] = args?.symbolCharset;
            resourceInputs["zxcvbnScoreThreshold"] = args?.zxcvbnScoreThreshold;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyPassword.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PolicyPassword resources.
 */
export interface PolicyPasswordState {
    amountDigits?: pulumi.Input<number>;
    amountLowercase?: pulumi.Input<number>;
    amountSymbols?: pulumi.Input<number>;
    amountUppercase?: pulumi.Input<number>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    checkHaveIBeenPwned?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    checkStaticRules?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    checkZxcvbn?: pulumi.Input<boolean>;
    errorMessage?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    executionLogging?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`">`1`</span>.
     */
    hibpAllowedCount?: pulumi.Input<number>;
    lengthMin?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`">`password`</span>.
     */
    passwordField?: pulumi.Input<string>;
    policyPasswordId?: pulumi.Input<string>;
    /**
     * Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
     */
    symbolCharset?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`">`2`</span>.
     */
    zxcvbnScoreThreshold?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a PolicyPassword resource.
 */
export interface PolicyPasswordArgs {
    amountDigits?: pulumi.Input<number>;
    amountLowercase?: pulumi.Input<number>;
    amountSymbols?: pulumi.Input<number>;
    amountUppercase?: pulumi.Input<number>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    checkHaveIBeenPwned?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    checkStaticRules?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    checkZxcvbn?: pulumi.Input<boolean>;
    errorMessage: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    executionLogging?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`">`1`</span>.
     */
    hibpAllowedCount?: pulumi.Input<number>;
    lengthMin?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`password`" pulumi-lang-dotnet="`Password`" pulumi-lang-go="`password`" pulumi-lang-python="`password`" pulumi-lang-yaml="`password`" pulumi-lang-java="`password`">`password`</span>.
     */
    passwordField?: pulumi.Input<string>;
    policyPasswordId?: pulumi.Input<string>;
    /**
     * Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
     */
    symbolCharset?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`">`2`</span>.
     */
    zxcvbnScoreThreshold?: pulumi.Input<number>;
}
