// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingSourceLdap extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingSourceLdap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingSourceLdapState, opts?: pulumi.CustomResourceOptions): PropertyMappingSourceLdap {
        return new PropertyMappingSourceLdap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingSourceLdap:PropertyMappingSourceLdap';

    /**
     * Returns true if the given object is an instance of PropertyMappingSourceLdap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingSourceLdap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingSourceLdap.__pulumiType;
    }

    declare public readonly expression: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly propertyMappingSourceLdapId: pulumi.Output<string>;

    /**
     * Create a PropertyMappingSourceLdap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingSourceLdapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingSourceLdapArgs | PropertyMappingSourceLdapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingSourceLdapState | undefined;
            resourceInputs["expression"] = state?.expression;
            resourceInputs["name"] = state?.name;
            resourceInputs["propertyMappingSourceLdapId"] = state?.propertyMappingSourceLdapId;
        } else {
            const args = argsOrState as PropertyMappingSourceLdapArgs | undefined;
            if (args?.expression === undefined && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            resourceInputs["expression"] = args?.expression;
            resourceInputs["name"] = args?.name;
            resourceInputs["propertyMappingSourceLdapId"] = args?.propertyMappingSourceLdapId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingSourceLdap.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingSourceLdap resources.
 */
export interface PropertyMappingSourceLdapState {
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingSourceLdapId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingSourceLdap resource.
 */
export interface PropertyMappingSourceLdapArgs {
    expression: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingSourceLdapId?: pulumi.Input<string>;
}
