// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingProviderMicrosoftEntra extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingProviderMicrosoftEntra resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingProviderMicrosoftEntraState, opts?: pulumi.CustomResourceOptions): PropertyMappingProviderMicrosoftEntra {
        return new PropertyMappingProviderMicrosoftEntra(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingProviderMicrosoftEntra:PropertyMappingProviderMicrosoftEntra';

    /**
     * Returns true if the given object is an instance of PropertyMappingProviderMicrosoftEntra.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingProviderMicrosoftEntra {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingProviderMicrosoftEntra.__pulumiType;
    }

    declare public readonly expression: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly propertyMappingProviderMicrosoftEntraId: pulumi.Output<string>;

    /**
     * Create a PropertyMappingProviderMicrosoftEntra resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingProviderMicrosoftEntraArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingProviderMicrosoftEntraArgs | PropertyMappingProviderMicrosoftEntraState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingProviderMicrosoftEntraState | undefined;
            resourceInputs["expression"] = state?.expression;
            resourceInputs["name"] = state?.name;
            resourceInputs["propertyMappingProviderMicrosoftEntraId"] = state?.propertyMappingProviderMicrosoftEntraId;
        } else {
            const args = argsOrState as PropertyMappingProviderMicrosoftEntraArgs | undefined;
            if (args?.expression === undefined && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            resourceInputs["expression"] = args?.expression;
            resourceInputs["name"] = args?.name;
            resourceInputs["propertyMappingProviderMicrosoftEntraId"] = args?.propertyMappingProviderMicrosoftEntraId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingProviderMicrosoftEntra.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingProviderMicrosoftEntra resources.
 */
export interface PropertyMappingProviderMicrosoftEntraState {
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderMicrosoftEntraId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingProviderMicrosoftEntra resource.
 */
export interface PropertyMappingProviderMicrosoftEntraArgs {
    expression: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderMicrosoftEntraId?: pulumi.Input<string>;
}
