// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingSaml extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingSaml resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingSamlState, opts?: pulumi.CustomResourceOptions): PropertyMappingSaml {
        return new PropertyMappingSaml(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingSaml:PropertyMappingSaml';

    /**
     * Returns true if the given object is an instance of PropertyMappingSaml.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingSaml {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingSaml.__pulumiType;
    }

    declare public readonly expression: pulumi.Output<string>;
    declare public readonly friendlyName: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly propertyMappingSamlId: pulumi.Output<string>;
    declare public readonly samlName: pulumi.Output<string>;

    /**
     * Create a PropertyMappingSaml resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingSamlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingSamlArgs | PropertyMappingSamlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingSamlState | undefined;
            resourceInputs["expression"] = state?.expression;
            resourceInputs["friendlyName"] = state?.friendlyName;
            resourceInputs["name"] = state?.name;
            resourceInputs["propertyMappingSamlId"] = state?.propertyMappingSamlId;
            resourceInputs["samlName"] = state?.samlName;
        } else {
            const args = argsOrState as PropertyMappingSamlArgs | undefined;
            if (args?.expression === undefined && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            if (args?.samlName === undefined && !opts.urn) {
                throw new Error("Missing required property 'samlName'");
            }
            resourceInputs["expression"] = args?.expression;
            resourceInputs["friendlyName"] = args?.friendlyName;
            resourceInputs["name"] = args?.name;
            resourceInputs["propertyMappingSamlId"] = args?.propertyMappingSamlId;
            resourceInputs["samlName"] = args?.samlName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingSaml.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingSaml resources.
 */
export interface PropertyMappingSamlState {
    expression?: pulumi.Input<string>;
    friendlyName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingSamlId?: pulumi.Input<string>;
    samlName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingSaml resource.
 */
export interface PropertyMappingSamlArgs {
    expression: pulumi.Input<string>;
    friendlyName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingSamlId?: pulumi.Input<string>;
    samlName: pulumi.Input<string>;
}
