// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingNotification extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingNotification resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingNotificationState, opts?: pulumi.CustomResourceOptions): PropertyMappingNotification {
        return new PropertyMappingNotification(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingNotification:PropertyMappingNotification';

    /**
     * Returns true if the given object is an instance of PropertyMappingNotification.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingNotification {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingNotification.__pulumiType;
    }

    declare public readonly expression: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly propertyMappingNotificationId: pulumi.Output<string>;

    /**
     * Create a PropertyMappingNotification resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingNotificationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingNotificationArgs | PropertyMappingNotificationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingNotificationState | undefined;
            resourceInputs["expression"] = state?.expression;
            resourceInputs["name"] = state?.name;
            resourceInputs["propertyMappingNotificationId"] = state?.propertyMappingNotificationId;
        } else {
            const args = argsOrState as PropertyMappingNotificationArgs | undefined;
            if (args?.expression === undefined && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            resourceInputs["expression"] = args?.expression;
            resourceInputs["name"] = args?.name;
            resourceInputs["propertyMappingNotificationId"] = args?.propertyMappingNotificationId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingNotification.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingNotification resources.
 */
export interface PropertyMappingNotificationState {
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingNotificationId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingNotification resource.
 */
export interface PropertyMappingNotificationArgs {
    expression: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingNotificationId?: pulumi.Input<string>;
}
