// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingProviderRac extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingProviderRac resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingProviderRacState, opts?: pulumi.CustomResourceOptions): PropertyMappingProviderRac {
        return new PropertyMappingProviderRac(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingProviderRac:PropertyMappingProviderRac';

    /**
     * Returns true if the given object is an instance of PropertyMappingProviderRac.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingProviderRac {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingProviderRac.__pulumiType;
    }

    declare public readonly expression: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly propertyMappingProviderRacId: pulumi.Output<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    declare public readonly settings: pulumi.Output<string | undefined>;

    /**
     * Create a PropertyMappingProviderRac resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PropertyMappingProviderRacArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingProviderRacArgs | PropertyMappingProviderRacState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingProviderRacState | undefined;
            resourceInputs["expression"] = state?.expression;
            resourceInputs["name"] = state?.name;
            resourceInputs["propertyMappingProviderRacId"] = state?.propertyMappingProviderRacId;
            resourceInputs["settings"] = state?.settings;
        } else {
            const args = argsOrState as PropertyMappingProviderRacArgs | undefined;
            resourceInputs["expression"] = args?.expression;
            resourceInputs["name"] = args?.name;
            resourceInputs["propertyMappingProviderRacId"] = args?.propertyMappingProviderRacId;
            resourceInputs["settings"] = args?.settings;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingProviderRac.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingProviderRac resources.
 */
export interface PropertyMappingProviderRacState {
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderRacId?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    settings?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingProviderRac resource.
 */
export interface PropertyMappingProviderRacArgs {
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderRacId?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
     */
    settings?: pulumi.Input<string>;
}
