// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SourceLdap extends pulumi.CustomResource {
    /**
     * Get an existing SourceLdap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SourceLdapState, opts?: pulumi.CustomResourceOptions): SourceLdap {
        return new SourceLdap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/sourceLdap:SourceLdap';

    /**
     * Returns true if the given object is an instance of SourceLdap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SourceLdap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SourceLdap.__pulumiType;
    }

    /**
     * Defaults to ``.
     */
    declare public readonly additionalGroupDn: pulumi.Output<string | undefined>;
    /**
     * Defaults to ``.
     */
    declare public readonly additionalUserDn: pulumi.Output<string | undefined>;
    declare public readonly baseDn: pulumi.Output<string>;
    declare public readonly bindCn: pulumi.Output<string>;
    declare public readonly bindPassword: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly deleteNotFoundObjects: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`member`" pulumi-lang-dotnet="`Member`" pulumi-lang-go="`member`" pulumi-lang-python="`member`" pulumi-lang-yaml="`member`" pulumi-lang-java="`member`">`member`</span>.
     */
    declare public readonly groupMembershipField: pulumi.Output<string | undefined>;
    /**
     * Defaults to `(objectClass=group)`.
     */
    declare public readonly groupObjectFilter: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly lookupGroupsFromUser: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Defaults to `objectSid`.
     */
    declare public readonly objectUniquenessField: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly passwordLoginUpdateInternalPassword: pulumi.Output<boolean | undefined>;
    declare public readonly propertyMappings: pulumi.Output<string[] | undefined>;
    declare public readonly propertyMappingsGroups: pulumi.Output<string[] | undefined>;
    declare public readonly serverUri: pulumi.Output<string>;
    declare public readonly slug: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly sni: pulumi.Output<boolean | undefined>;
    declare public readonly sourceLdapId: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly startTls: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly syncGroups: pulumi.Output<boolean | undefined>;
    declare public readonly syncParentGroup: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly syncUsers: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    declare public readonly syncUsersPassword: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `distinguishedName`.
     */
    declare public readonly userMembershipAttribute: pulumi.Output<string | undefined>;
    /**
     * Defaults to `(objectClass=person)`.
     */
    declare public readonly userObjectFilter: pulumi.Output<string | undefined>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    declare public readonly userPathTemplate: pulumi.Output<string | undefined>;
    /**
     * Generated.
     */
    declare public readonly uuid: pulumi.Output<string>;

    /**
     * Create a SourceLdap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SourceLdapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SourceLdapArgs | SourceLdapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SourceLdapState | undefined;
            resourceInputs["additionalGroupDn"] = state?.additionalGroupDn;
            resourceInputs["additionalUserDn"] = state?.additionalUserDn;
            resourceInputs["baseDn"] = state?.baseDn;
            resourceInputs["bindCn"] = state?.bindCn;
            resourceInputs["bindPassword"] = state?.bindPassword;
            resourceInputs["deleteNotFoundObjects"] = state?.deleteNotFoundObjects;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["groupMembershipField"] = state?.groupMembershipField;
            resourceInputs["groupObjectFilter"] = state?.groupObjectFilter;
            resourceInputs["lookupGroupsFromUser"] = state?.lookupGroupsFromUser;
            resourceInputs["name"] = state?.name;
            resourceInputs["objectUniquenessField"] = state?.objectUniquenessField;
            resourceInputs["passwordLoginUpdateInternalPassword"] = state?.passwordLoginUpdateInternalPassword;
            resourceInputs["propertyMappings"] = state?.propertyMappings;
            resourceInputs["propertyMappingsGroups"] = state?.propertyMappingsGroups;
            resourceInputs["serverUri"] = state?.serverUri;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["sni"] = state?.sni;
            resourceInputs["sourceLdapId"] = state?.sourceLdapId;
            resourceInputs["startTls"] = state?.startTls;
            resourceInputs["syncGroups"] = state?.syncGroups;
            resourceInputs["syncParentGroup"] = state?.syncParentGroup;
            resourceInputs["syncUsers"] = state?.syncUsers;
            resourceInputs["syncUsersPassword"] = state?.syncUsersPassword;
            resourceInputs["userMembershipAttribute"] = state?.userMembershipAttribute;
            resourceInputs["userObjectFilter"] = state?.userObjectFilter;
            resourceInputs["userPathTemplate"] = state?.userPathTemplate;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as SourceLdapArgs | undefined;
            if (args?.baseDn === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseDn'");
            }
            if (args?.bindCn === undefined && !opts.urn) {
                throw new Error("Missing required property 'bindCn'");
            }
            if (args?.bindPassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'bindPassword'");
            }
            if (args?.serverUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverUri'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["additionalGroupDn"] = args?.additionalGroupDn;
            resourceInputs["additionalUserDn"] = args?.additionalUserDn;
            resourceInputs["baseDn"] = args?.baseDn;
            resourceInputs["bindCn"] = args?.bindCn;
            resourceInputs["bindPassword"] = args?.bindPassword ? pulumi.secret(args.bindPassword) : undefined;
            resourceInputs["deleteNotFoundObjects"] = args?.deleteNotFoundObjects;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["groupMembershipField"] = args?.groupMembershipField;
            resourceInputs["groupObjectFilter"] = args?.groupObjectFilter;
            resourceInputs["lookupGroupsFromUser"] = args?.lookupGroupsFromUser;
            resourceInputs["name"] = args?.name;
            resourceInputs["objectUniquenessField"] = args?.objectUniquenessField;
            resourceInputs["passwordLoginUpdateInternalPassword"] = args?.passwordLoginUpdateInternalPassword;
            resourceInputs["propertyMappings"] = args?.propertyMappings;
            resourceInputs["propertyMappingsGroups"] = args?.propertyMappingsGroups;
            resourceInputs["serverUri"] = args?.serverUri;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["sni"] = args?.sni;
            resourceInputs["sourceLdapId"] = args?.sourceLdapId;
            resourceInputs["startTls"] = args?.startTls;
            resourceInputs["syncGroups"] = args?.syncGroups;
            resourceInputs["syncParentGroup"] = args?.syncParentGroup;
            resourceInputs["syncUsers"] = args?.syncUsers;
            resourceInputs["syncUsersPassword"] = args?.syncUsersPassword;
            resourceInputs["userMembershipAttribute"] = args?.userMembershipAttribute;
            resourceInputs["userObjectFilter"] = args?.userObjectFilter;
            resourceInputs["userPathTemplate"] = args?.userPathTemplate;
            resourceInputs["uuid"] = args?.uuid;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bindPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SourceLdap.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SourceLdap resources.
 */
export interface SourceLdapState {
    /**
     * Defaults to ``.
     */
    additionalGroupDn?: pulumi.Input<string>;
    /**
     * Defaults to ``.
     */
    additionalUserDn?: pulumi.Input<string>;
    baseDn?: pulumi.Input<string>;
    bindCn?: pulumi.Input<string>;
    bindPassword?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    deleteNotFoundObjects?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`member`" pulumi-lang-dotnet="`Member`" pulumi-lang-go="`member`" pulumi-lang-python="`member`" pulumi-lang-yaml="`member`" pulumi-lang-java="`member`">`member`</span>.
     */
    groupMembershipField?: pulumi.Input<string>;
    /**
     * Defaults to `(objectClass=group)`.
     */
    groupObjectFilter?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    lookupGroupsFromUser?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    /**
     * Defaults to `objectSid`.
     */
    objectUniquenessField?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    passwordLoginUpdateInternalPassword?: pulumi.Input<boolean>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    serverUri?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    sni?: pulumi.Input<boolean>;
    sourceLdapId?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    startTls?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncGroups?: pulumi.Input<boolean>;
    syncParentGroup?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncUsers?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncUsersPassword?: pulumi.Input<boolean>;
    /**
     * Defaults to `distinguishedName`.
     */
    userMembershipAttribute?: pulumi.Input<string>;
    /**
     * Defaults to `(objectClass=person)`.
     */
    userObjectFilter?: pulumi.Input<string>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    userPathTemplate?: pulumi.Input<string>;
    /**
     * Generated.
     */
    uuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SourceLdap resource.
 */
export interface SourceLdapArgs {
    /**
     * Defaults to ``.
     */
    additionalGroupDn?: pulumi.Input<string>;
    /**
     * Defaults to ``.
     */
    additionalUserDn?: pulumi.Input<string>;
    baseDn: pulumi.Input<string>;
    bindCn: pulumi.Input<string>;
    bindPassword: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    deleteNotFoundObjects?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`member`" pulumi-lang-dotnet="`Member`" pulumi-lang-go="`member`" pulumi-lang-python="`member`" pulumi-lang-yaml="`member`" pulumi-lang-java="`member`">`member`</span>.
     */
    groupMembershipField?: pulumi.Input<string>;
    /**
     * Defaults to `(objectClass=group)`.
     */
    groupObjectFilter?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    lookupGroupsFromUser?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    /**
     * Defaults to `objectSid`.
     */
    objectUniquenessField?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    passwordLoginUpdateInternalPassword?: pulumi.Input<boolean>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    serverUri: pulumi.Input<string>;
    slug: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    sni?: pulumi.Input<boolean>;
    sourceLdapId?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    startTls?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncGroups?: pulumi.Input<boolean>;
    syncParentGroup?: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncUsers?: pulumi.Input<boolean>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
     */
    syncUsersPassword?: pulumi.Input<boolean>;
    /**
     * Defaults to `distinguishedName`.
     */
    userMembershipAttribute?: pulumi.Input<string>;
    /**
     * Defaults to `(objectClass=person)`.
     */
    userObjectFilter?: pulumi.Input<string>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    userPathTemplate?: pulumi.Input<string>;
    /**
     * Generated.
     */
    uuid?: pulumi.Input<string>;
}
