// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageSource extends pulumi.CustomResource {
    /**
     * Get an existing StageSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageSourceState, opts?: pulumi.CustomResourceOptions): StageSource {
        return new StageSource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageSource:StageSource';

    /**
     * Returns true if the given object is an instance of StageSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageSource.__pulumiType;
    }

    declare public readonly name: pulumi.Output<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
     */
    declare public readonly resumeTimeout: pulumi.Output<string | undefined>;
    declare public readonly source: pulumi.Output<string | undefined>;
    declare public readonly stageSourceId: pulumi.Output<string>;

    /**
     * Create a StageSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageSourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageSourceArgs | StageSourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageSourceState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["resumeTimeout"] = state?.resumeTimeout;
            resourceInputs["source"] = state?.source;
            resourceInputs["stageSourceId"] = state?.stageSourceId;
        } else {
            const args = argsOrState as StageSourceArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["resumeTimeout"] = args?.resumeTimeout;
            resourceInputs["source"] = args?.source;
            resourceInputs["stageSourceId"] = args?.stageSourceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageSource.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageSource resources.
 */
export interface StageSourceState {
    name?: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
     */
    resumeTimeout?: pulumi.Input<string>;
    source?: pulumi.Input<string>;
    stageSourceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StageSource resource.
 */
export interface StageSourceArgs {
    name?: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
     */
    resumeTimeout?: pulumi.Input<string>;
    source?: pulumi.Input<string>;
    stageSourceId?: pulumi.Input<string>;
}
