// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageConsent extends pulumi.CustomResource {
    /**
     * Get an existing StageConsent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageConsentState, opts?: pulumi.CustomResourceOptions): StageConsent {
        return new StageConsent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageConsent:StageConsent';

    /**
     * Returns true if the given object is an instance of StageConsent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageConsent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageConsent.__pulumiType;
    }

    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `weeks=4`.
     */
    declare public readonly consentExpireIn: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>
     *   - <span pulumi-lang-nodejs="`permanent`" pulumi-lang-dotnet="`Permanent`" pulumi-lang-go="`permanent`" pulumi-lang-python="`permanent`" pulumi-lang-yaml="`permanent`" pulumi-lang-java="`permanent`">`permanent`</span>
     *   - <span pulumi-lang-nodejs="`expiring`" pulumi-lang-dotnet="`Expiring`" pulumi-lang-go="`expiring`" pulumi-lang-python="`expiring`" pulumi-lang-yaml="`expiring`" pulumi-lang-java="`expiring`">`expiring`</span>
     *  Defaults to <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>.
     */
    declare public readonly mode: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly stageConsentId: pulumi.Output<string>;

    /**
     * Create a StageConsent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageConsentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageConsentArgs | StageConsentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageConsentState | undefined;
            resourceInputs["consentExpireIn"] = state?.consentExpireIn;
            resourceInputs["mode"] = state?.mode;
            resourceInputs["name"] = state?.name;
            resourceInputs["stageConsentId"] = state?.stageConsentId;
        } else {
            const args = argsOrState as StageConsentArgs | undefined;
            resourceInputs["consentExpireIn"] = args?.consentExpireIn;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["name"] = args?.name;
            resourceInputs["stageConsentId"] = args?.stageConsentId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageConsent.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageConsent resources.
 */
export interface StageConsentState {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `weeks=4`.
     */
    consentExpireIn?: pulumi.Input<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>
     *   - <span pulumi-lang-nodejs="`permanent`" pulumi-lang-dotnet="`Permanent`" pulumi-lang-go="`permanent`" pulumi-lang-python="`permanent`" pulumi-lang-yaml="`permanent`" pulumi-lang-java="`permanent`">`permanent`</span>
     *   - <span pulumi-lang-nodejs="`expiring`" pulumi-lang-dotnet="`Expiring`" pulumi-lang-go="`expiring`" pulumi-lang-python="`expiring`" pulumi-lang-yaml="`expiring`" pulumi-lang-java="`expiring`">`expiring`</span>
     *  Defaults to <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>.
     */
    mode?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    stageConsentId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StageConsent resource.
 */
export interface StageConsentArgs {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `weeks=4`.
     */
    consentExpireIn?: pulumi.Input<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>
     *   - <span pulumi-lang-nodejs="`permanent`" pulumi-lang-dotnet="`Permanent`" pulumi-lang-go="`permanent`" pulumi-lang-python="`permanent`" pulumi-lang-yaml="`permanent`" pulumi-lang-java="`permanent`">`permanent`</span>
     *   - <span pulumi-lang-nodejs="`expiring`" pulumi-lang-dotnet="`Expiring`" pulumi-lang-go="`expiring`" pulumi-lang-python="`expiring`" pulumi-lang-yaml="`expiring`" pulumi-lang-java="`expiring`">`expiring`</span>
     *  Defaults to <span pulumi-lang-nodejs="`alwaysRequire`" pulumi-lang-dotnet="`AlwaysRequire`" pulumi-lang-go="`alwaysRequire`" pulumi-lang-python="`always_require`" pulumi-lang-yaml="`alwaysRequire`" pulumi-lang-java="`alwaysRequire`">`always_require`</span>.
     */
    mode?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    stageConsentId?: pulumi.Input<string>;
}
