// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageInvitation extends pulumi.CustomResource {
    /**
     * Get an existing StageInvitation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageInvitationState, opts?: pulumi.CustomResourceOptions): StageInvitation {
        return new StageInvitation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageInvitation:StageInvitation';

    /**
     * Returns true if the given object is an instance of StageInvitation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageInvitation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageInvitation.__pulumiType;
    }

    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly continueFlowWithoutInvitation: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly stageInvitationId: pulumi.Output<string>;

    /**
     * Create a StageInvitation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageInvitationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageInvitationArgs | StageInvitationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageInvitationState | undefined;
            resourceInputs["continueFlowWithoutInvitation"] = state?.continueFlowWithoutInvitation;
            resourceInputs["name"] = state?.name;
            resourceInputs["stageInvitationId"] = state?.stageInvitationId;
        } else {
            const args = argsOrState as StageInvitationArgs | undefined;
            resourceInputs["continueFlowWithoutInvitation"] = args?.continueFlowWithoutInvitation;
            resourceInputs["name"] = args?.name;
            resourceInputs["stageInvitationId"] = args?.stageInvitationId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageInvitation.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageInvitation resources.
 */
export interface StageInvitationState {
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    continueFlowWithoutInvitation?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    stageInvitationId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StageInvitation resource.
 */
export interface StageInvitationArgs {
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    continueFlowWithoutInvitation?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    stageInvitationId?: pulumi.Input<string>;
}
