---
images:
- name: linuxserver/sonarr
  newName: lscr.io/linuxserver/sonarr
  newTag: version-4.0.20.3014@sha256:f247545d23ba8b233d6604575347e48a623fe6ad75dda02348bf81917f3b5c06
labels:
- pairs:
    "app.kubernetes.io/name": sonarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
