---
images:
- name: linuxserver/sonarr
  newName: lscr.io/linuxserver/sonarr
  newTag: version-4.0.19.2979@sha256:4d9df314875e1249ab7d6170c2b9b3dc1d8e6383f168ceb10dc9a5ad9b324739
labels:
- pairs:
    "app.kubernetes.io/name": sonarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
