---
images:
- name: linuxserver/sonarr
  newName: lscr.io/linuxserver/sonarr
  newTag: version-4.0.19.2979@sha256:4b025354d338999e03bf6dbdadcdde94815d39d4a5aba5de3cdc86a56d7d6c51
labels:
- pairs:
    "app.kubernetes.io/name": sonarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
