---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
configMapGenerator:
- name: openclaw-sandbox-config
  files:
  - seed.sh=config/seed.sh
  - entrypoint.sh=config/entrypoint.sh
  - sshd_config=config/sshd_config
commonLabels:
  app.kubernetes.io/name: openclaw-sandbox
  app.kubernetes.io/instance: openclaw-sandbox
