---
images:
- name: esphome/esphome
  newTag: 2026.4.3@sha256:d9da091d4d2fc072d238177ce07e02a6cc014b31677da653a36ac68dd6caaccd
resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- httproute.yaml
commonLabels:
  app.kubernetes.io/name: esphome
