---
images:
- name: esphome/esphome
  newTag: 2026.4.2@sha256:79a0778593a5664c95530c001ed1abe7cb4cee6e865977f030f5b22b4d18acd8
resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- httproute.yaml
commonLabels:
  app.kubernetes.io/name: esphome
