---
images:
- name: esphome/esphome
  newTag: 2026.5.2@sha256:1609bf4826b4625e5654c56e4aa86d3f92372beea4772b071fc8a0397edaa72b
resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- httproute.yaml
commonLabels:
  app.kubernetes.io/name: esphome
