---
images:
- name: linuxserver/radarr
  newName: lscr.io/linuxserver/radarr
  newTag: version-6.1.1.10360@sha256:15417a594ebda4c660a9fa9748e7199d33e2d17b31bbc5ad7ba2e86f0b414763
labels:
- pairs:
    "app.kubernetes.io/name": radarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
