---
images:
- name: linuxserver/radarr
  newName: lscr.io/linuxserver/radarr
  newTag: version-6.1.1.10360@sha256:b01097ad2d948c9f5eca39eb60bb529e2e55b0738c4bf7db09383bef0abab59d
labels:
- pairs:
    "app.kubernetes.io/name": radarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
