---
images:
- name: linuxserver/radarr
  newName: lscr.io/linuxserver/radarr
  newTag: version-6.1.1.10360@sha256:6f1dda18354ea7f28cead8f6d099fc8222498c3ae165f567d504ed04d70980d7
labels:
- pairs:
    "app.kubernetes.io/name": radarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
