---
images:
- name: linuxserver/prowlarr
  newName: lscr.io/linuxserver/prowlarr
  newTag: version-2.3.5.5327@sha256:a89f252d6a22bd25af14a5380aec0adcc3c3af2e3282164f981680e6844070f3
labels:
- pairs:
    "app.kubernetes.io/name": prowlarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
