---
images:
- name: linuxserver/prowlarr
  newName: lscr.io/linuxserver/prowlarr
  newTag: version-2.5.2.5491@sha256:91844fa2c927ad6ede5630127183cc7868b175f6223e83e6a5da1fffea2aa782
labels:
- pairs:
    "app.kubernetes.io/name": prowlarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
