---
images:
- name: linuxserver/prowlarr
  newName: lscr.io/linuxserver/prowlarr
  newTag: version-2.5.2.5491@sha256:aaa16ba7d66e413db6d0358d3b6c68d833578ba7f176f24a51807181e7637fce
labels:
- pairs:
    "app.kubernetes.io/name": prowlarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
