---
images:
- name: ipfs/kubo
  newTag: v0.43.0@sha256:63f5502f7a01b82a675e45bae81b2f5dfa90248ec4a86cd0a58c218347e1f2d2
labels:
- pairs:
    "app.kubernetes.io/name": ipfs-kubo
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- ipfs-api-httproute.yaml
- ipfs-gateway-cert.yaml
- ipfs-gateway-gateway.yaml
- ipfs-gateway-httproute.yaml
