---
images:
- name: ipfs/kubo
  newTag: v0.42.0@sha256:8907cb0cc1ad5798f6bb1bb1341a800990c268e021cedfa317e8aa1a33864214
labels:
- pairs:
    "app.kubernetes.io/name": ipfs-kubo
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- ipfs-api-httproute.yaml
- ipfs-gateway-cert.yaml
- ipfs-gateway-gateway.yaml
- ipfs-gateway-httproute.yaml
