---
images:
- name: ipfs/kubo
  newTag: v0.40.1@sha256:9c70a3dba0b5f362bf99317a02384a194f5c91cf5388abdb8fe7d64d83dd20bb
labels:
- pairs:
    "app.kubernetes.io/name": ipfs-kubo
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- ciliumnetworkpolicy.yaml
- ipfs-api-httproute.yaml
- ipfs-gateway-cert.yaml
- ipfs-gateway-gateway.yaml
- ipfs-gateway-httproute.yaml
