---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: velero-chart
  namespace: velero
spec:
  interval: 24h
  url: oci://harbor.services.home.yrf.me/chartproxy/vmware-tanzu.github.io/helm-charts/velero
  ref:
    tag: 11.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chartRef:
    kind: OCIRepository
    name: velero-chart
  interval: 15m
  values:
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.13.2
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    metrics:
      serviceMonitor:
        enabled: true
      nodeAgentPodMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    configuration:
      extraEnvVars:
      - name: TZ
        value: Asia/Kuala_Lumpur
      backupStorageLocation:
      - name: okinawa-s3
        provider: aws
        bucket: rfhome-velero-backup
        prefix: pathweb/
        default: true
        accessMode: ReadWrite
        credential:
          name: velero-okinawa-s3-credentials
          key: credentials
        config:
          region: us-east-1
          s3Url: https://okinawa-s3.services.home.yrf.me:7070
      volumeSnapshotLocation: []
      defaultSnapshotMoveData: true
      features: "EnableCSI"
    credentials:
      useSecret: false
    deployNodeAgent: true
    nodeAgent:
      priorityClassName: system-node-critical
