---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: slzb-ultima-wg-iot-network
  namespace: home-network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "iot",
          "ipam": {
            "type": "static",
            "addresses": [
              {"address": "10.229.4.5/24", "gateway": "10.229.4.1"},
              {"address": "fd96:619:803e:3700::5/64", "gateway": "fd96:619:803e:3700::1"}
            ]
          }
        },
        {
          "type": "tuning",
          "sysctl": {
            "net.ipv6.conf.IFNAME.accept_ra": "1",
            "net.ipv6.conf.IFNAME.autoconf": "1"
          }
        }
      ]
    }
