---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slzb-ultima-wg-secrets
  namespace: home-network
spec:
  encryptedData:
    wireproxy.conf: AgAvkv3Lu/sNO49dfe0MsM4JmgY4eIT8CgNbHq1JH60rbDd+h2NdTWLZc6UKIT3VXT5ifSCLJ/BOwPk5Lwor4vHXRk5id9IIIR6764Nb1f9pwHpt+w3GpAFIBpo8wRrEZUzP5uuk/G2cwzf4/ssnjTrkZeXzgr2of+prlELPl6h92Zwg6AFveOG5qkwhNFRkCIUm941UHtWULgLOToGmJX3ZVAukfieVuXbpTWxp29qM/SQRH+bCuVIjw9xIczqsSf+RCuebLQL1050O5YKlfzvSGgf8BkXlGAmL0a9G7ZJWRe0ThZojIydvjxF9BbqAGVBIMhMeoXCp/Ld954Oun85Um9x+mOHT+rAi3W3VdTnzBv1w/4RZDC8uMBrJauQ1D+w+QNccuTBVZrupb93Dzf0Xq5YXS+0gNMHwdnisFaGLBu484bqCJaEsEteZ5t095CnjLTpiycqfocXr/YwEhAUEGFYp6xowAbNyzwob7AXa7ObWo7utuma6yUmc5wMlZnYreVuWS8F3OH9kv9MEuiDxkggmbLJnkCnz4Wm4TY207E9GjUsiI4I9EPkaCBVY6G1RSH97jnsYZFvSboPgH8+TCUSkwrx14U94zAjyU+3UWsotnRp6de9ePEdBvJIW6w+708dIcsMBz0DelLhZXv1XNbkvmeRHtpYE0BYCRrKIVm2R/55013Ok5ghypun+42nkmJN315dZMrkQko+22GuDxjy3nUQz/iHd6NKzH2SeItFTA3wDwYY30Zw/0pTHidG4Fdik5Vd+x94Nl4TFkABdMiyNlJMwZT8sJhrHxYMsWLGZXV7dSD9GPBuz7pZpWc5ofWG3os27wEam3pcHRMbwGzuvcK4DQMhwXwGLaUGWZFL1XBA6dYS3l7MFQf1umfukiRZ6GFkQlo419d4a5t96onnImAMpZbGzoSfR1ajErxSO1jRFoFGWq/MIM+JtDub4nSTfomXlxkn9VNpsCcNawee79Slc/klsP8sYwb3LkRv4Jnfol8tKrVJ1vQlTelyjzO1ONK/X8DgSjuGyBWK93dAsztpR6G9XXXV1YMrDl4jTOwxQPcf0tkrq82/AFZ+V8J5ionuLFlpdhbfCwrgBKGGU/EUMPffF1mmlRC3k+GAi/NloOuh0Et6H41K9EUak+n9h0il6u+FG+SWjx8gaEkD9MBriJR7x70imkvwbtSH7aGgGbT3YnPxqyjhaFA6wr4ByU3VJF0mUAWWxmWAcxIyPMKEmfYqt7y4Yy84Y4p6x9mBeL2JKJZD+TXxV3jPVE+5QcfajFxoHMC99iZnZ45lsQBpGoC46y+EFWuk+nDgMY5N8+uflh3ZkikWNp24Rjd/up40Yu08btA==
  template:
    metadata:
      name: slzb-ultima-wg-secrets
      namespace: home-network
    type: Opaque
