---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slzb-ultima-wg-secrets
  namespace: home-network
spec:
  encryptedData:
    wireproxy.conf: AgCKk6Izev4Xa/y/gHWgLZIIwzEO8I/SQuFE0xVYxNDleHATJzHfd2WFi/9TdXgFwoUmP32SW7PXcyxyNibBatBu3KZI0XkzmgjLgdeD55EC5Ro9OdW9mvoRiZvX34dE6sF0cVG303V3AJI/Ga45Gg/Q/x5F0sywe57CUd8VLgJOBRfdhxVdfGpZnG9DK6kN2/ZCRpztnhIOVCSexYb3LJLqI+9tKYbpOCjs5MdzE0H2PRk2+0/j7Xk7bBgU7dewtJoaGDEx7MQp/rGq6fb8V9JYbY6h0vbtOpsRBYvwOXoMOr7wKoFJIfJS9GVV3j0eq+wfdC66koUp3Kx+S41N2BCITA7XcI4qGdX8InHvROQ0Ps50R6jGS+iR2D7JX2vcEaQ1TPT7DNJObklu/wlAhNNSrzqU9Ioe/cMLWVHfmfjnlHH3tsm5/EB5oqPRfjR4kfQck7JGmnlnCo73sOjHvach3yk6rQ4HaiIleBb7plDCkR6ImucU3iFEk3WK6jhfXNKVE9uzzBZypMn7Ly4oDdkaQsU/Ah/ch5KXf53leq3DCNqL4bFFW4aFXfze2BXi19bWepBllONbfDcdBxiMp+dsiMK5tQYp+0ZwGY9m69r12Gyt2vsbnJihFVXI7KvN6mvLT7pkmJsBzXo41HRMNre8qTfBnlNhKZEhk+jKy1johOjgngZ2Om0eNu23x78/V76Qum4ungFNPihqY3whAagwuIFmB+y2GL0HLyNSl+aVg0yixXDXUXXep4WileE9IVrmERqhTp2bh3v3lc9nNvzST9Y6P8dDrP6ATj2q7/FGj9uVNDx7YcQzwZ8UpJLgpOHUEmrBfYJc8yd7k7JnjQNHSd4ToaWohc/VD3wrq6FmQvxMZLFfTeykULJDxKsgyRiij8e68tLaPQQc+fd0zgOIeVL3ml1leBZfZeVasjpT53dytwvHTD6+JSt/O0KqjAYSZW1HEF+UN69ykTeitmJNnTFYBzkACg0Dn9To/Fi4pPOIWlgFg9YYQV/RVQDW9TOoSOVrH5l2mcEWIk04rZ1Zx0AS9yMRkEmTGwEc68DKpKcis4qFbLuYAWDGGR8cqAz3L6XVpcmHu+BcrxYGfUJkSif5P8t5QUNFy73sfN+bGd/N0gO95qSRa5AqcumaRLAXQa1ET4r7Y6AB6Omq78a6P0chHihYw41qrWle4uYraZVsN5dznIB7T6crsKUehZIvA24QhAV1pufY9xYj60UlC4tQvOXMkF/j3p448JRxG19wDQv8d17Or6OSByjhaSqdnkdW0UECgMBZWwGU17YCImdylzIwl1rUN75wqmmcQrNDldWOROWsxgcj2m4YxNU=
  template:
    metadata:
      name: slzb-ultima-wg-secrets
      namespace: home-network
    type: Opaque
