---
images:
- name: linuxserver/lidarr
  newName: lscr.io/linuxserver/lidarr
  newTag: version-3.1.0.4875@sha256:94a876d1581f2ae5af5b846320d5f6f7a102a4755939ce0b43b01c60f9f86056
labels:
- pairs:
    "app.kubernetes.io/name": lidarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
