---
images:
- name: linuxserver/lidarr
  newName: lscr.io/linuxserver/lidarr
  newTag: version-3.1.0.4875@sha256:e9a275176e8158638395cc8574b02b7695006f70bde48830a09fa6ab5b6775df
labels:
- pairs:
    "app.kubernetes.io/name": lidarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
