---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/anszom/rethink
  newTag: dev@sha256:2266da6c79a775ca61c9b6059d59d38b65d8d388b82c628dc4b60dde01676f95
- name: mikefarah/yq
  newTag: 4.53.6@sha256:cfc4eee658595834ef304eadb0c3ea721f3b7cb6404ad8b7cb909cc5b5145b23
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
- rethink-secrets.sealed.yaml
configMapGenerator:
- name: rethink-cloud-config
  files:
  - config.json
labels:
- pairs:
    app.kubernetes.io/name: rethink-cloud
  includeTemplates: true
  includeSelectors: true
