---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/anszom/rethink
  newTag: dev@sha256:648b40418788169284bc0f300cf61d57fa8225df4109ca9e7aff6ed13906d6a9
- name: mikefarah/yq
  newTag: 4.53.6@sha256:cfc4eee658595834ef304eadb0c3ea721f3b7cb6404ad8b7cb909cc5b5145b23
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
- rethink-secrets.sealed.yaml
configMapGenerator:
- name: rethink-cloud-config
  files:
  - config.json
labels:
- pairs:
    app.kubernetes.io/name: rethink-cloud
  includeTemplates: true
  includeSelectors: true
