---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rethink-secrets
  namespace: home-network
spec:
  encryptedData:
    MQTT_PASS: AgAQFUrfdFp9nUJ1cIQ4lVeXmTMbqJWW2eL0DNvHj2yWM7sTlDQjGcmHFADz6D2gjbMZ9ViI4WPcVwyLqu850k20bC0Q91p062RgCFbqghhbaoA3vF/rrkkatobv8C/DAGNlLqdPVSCQ4AiTXPNoVvt7DjUq2LlgX9XYISxDUKOtQGsWzfpsq2bTy+igVGgKdNrbKrPhoLWSXTCbcBNBqc1vlRblbldmCbDFJenx3ulZuJAARAKG6dflwyZh+06YFMgnPSclIc+UUB6gquaaSYNSoeZA2oOUV6ieOwcDX0I0gEC966YND1NI7MFjDQjjNykz7wAFZ54Bo8YSHrxAz0XaKgyFveAFh6pJUDnWEjBQPhGZVMI51CV/+DpE21vCv3eqs7urVCYG3/PIQLSclx28CXwQsPlWznh+kqpmjJZapM3i6AAUiqxky+z6GuOBSF410m2YmSQlATz1erc4CMTlrMdhcb2RvNKOGeAH+wzrntBLsKgo7vXah5tsgj1k1gIjeSGSEyBE0n6mjh/dGLlv425eiywddjDlfL1CT38v+RW9ludxGTO3rWYwl0upQAmuuAKmbrGCcGXTCLm8aVPg3zDlJFDdrRKVSNwWS32y7sugzC2vUzLzsjnqyx2G2HmykAVH0A4W+tcD4a/OOehMMXTIfDTWwWGVyb1SBJ8Hc07EBr+4XXxBPCYB6wHQ7YP5W8r0qCD+RxVFE6uvVnpUzKHgLV+rMqn7XAn5OfaNeLypebI=
    MQTT_USER: AgB9aWMYx9+v0IncS6G/yFNvLoF/fFXNgOhQWKLOsIrv7YGtB2yIRNRZo9ZytlSh0sKIlYAHPCrcC8UFp3gexwoWX/dUNNajlUCusuOI0rxoheG4VdxeKwI1ut2UdulmLNQFJZ97OV90y3Qfh0xAxQOLq+yYdIP2y8AqoIHVZYOnR7HmFyl/ucPvfo+JwrT4Y8UizKriOE8WQpm+nqVZQYvy6K4kWdUs1AOaiTUaIIgqAGLly6ut7uENSAm8u+x5Yqi9q3OM0x8gY+z8+jy4eEsAULBNfK/7SmBSuC2N2gbg1G2MSyTimwHJbVw/4orWjKqgnhTaeNkPp8oedp2IV7+ggOMVj8OcBpZQV94j8EKm1kMW/5tQ1vcCn54a8kmPjypuxbTi0QhHWchsa+0Vkjn7hmd/XIhIwLteS3tjGukyqQOLRJev21ykMA0tpFSoxyOLX3MSSNEzr2MG+ZdGF9nA+5XDTskvGhs0og2Z5iKT8lqrqnWUKUlEYv2VZt1/gjcFgUZg9+7568jOQBC8QKf9YrgdERRvC9a1vhs3mUwclmAbs6+EybuDuCdWJKJtpLOQkLx6CvmbRJp7Utqozbv9+OsaeEC+iGwIeAtc60zx2SiXS8vZ4DNQQN32NSkwa0IJmIZjY0WGJkmS/7flIGrBPaT5nQ8Xi17wx65qR4q/gvle5ClIQ7JhBKUchM0WHi8vYTa32BU5Krsm4MQD
  template:
    metadata:
      name: rethink-secrets
      namespace: home-network
    type: Opaque
