---
images:
- name: rhasspy/wyoming-piper
  newTag: 2.5.1@sha256:a61b12575e5a05b307983c3172bdf03ef7dd68a6f6093f3b6105a0c65004d0a3
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
