---
images:
- name: rhasspy/wyoming-piper
  newTag: 2.5.0@sha256:765ed9fb6cb96dc36d687ada7b90fe846bd3219bc005192e0bdf192d8ad48692
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
- ciliumnetworkpolicy.yaml
