---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/music-assistant/server
  newTag: 2.9.5@sha256:d5f2e4e7ef2b9798b554c1ad79b0444728606d8f68f8b151f64621934d80ef65
- name: mikefarah/yq
  newTag: 4.53.3@sha256:11a1f0b604b13dbbdc662260d8db6f644b22d8553122a25c1b5b2e8713ca6977
- name: brainicism/bgutil-ytdlp-pot-provider
  newTag: 1.3.1@sha256:1aaa43a0ca72dfca6a6d2129a0fb4a23465c25adb1b043f8aff829a20825646b
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
labels:
- pairs:
    app.kubernetes.io/name: music-assistant
  includeTemplates: true
  includeSelectors: false
