---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/music-assistant/server
  newTag: 2.8.2
- name: mikefarah/yq
  newTag: 4.52.5
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
labels:
- pairs:
    app.kubernetes.io/name: music-assistant
  includeTemplates: true
  includeSelectors: false
