---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/music-assistant/server
  newTag: latest
resources:
- statefulset.yaml
- service.yaml
- networkattachmentdefinition.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
labels:
- pairs:
    app.kubernetes.io/name: music-assistant
  includeTemplates: true
  includeSelectors: false
