---
apiVersion: v1
kind: Service
metadata:
  name: music-assistant
  namespace: media-services
spec:
  selector:
    app.kubernetes.io/name: music-assistant
  clusterIP: None
  ports:
  - port: 8095
    targetPort: 8095
    name: http
    protocol: TCP
    appProtocol: http
  - port: 8097
    targetPort: 8097
    name: streaming
    protocol: TCP
    appProtocol: http
