---
images:
- name: linuxserver/bazarr
  newName: lscr.io/linuxserver/bazarr
  newTag: version-v1.5.6@sha256:d736df5df0286373a26d34f47aa413cb8aeada74f6338dac372a6d37ba1b3b0d
labels:
- pairs:
    "app.kubernetes.io/name": bazarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
