---
images:
- name: linuxserver/bazarr
  newName: lscr.io/linuxserver/bazarr
  newTag: version-v1.5.6@sha256:7563f01bf27554df58e10544a4bb83479258883315a31cd1c929293e908144d0
labels:
- pairs:
    "app.kubernetes.io/name": bazarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
