---
images:
- name: linuxserver/bazarr
  newName: lscr.io/linuxserver/bazarr
  newTag: version-v1.5.6@sha256:aaaa087af75a73b7ac765dcc5d748874cfafdb93c23ec9f64fbb481dea291b23
labels:
- pairs:
    "app.kubernetes.io/name": bazarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
