---
images:
- name: linuxserver/calibre
  newName: lscr.io/linuxserver/calibre
  newTag: version-v9.8.0@sha256:de295215232855535ec110855d2f74946c7d78a596eb3a9d39d191e21dbc6fcc
labels:
- pairs:
    "app.kubernetes.io/name": calibre
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- okinawa-media-books.yaml
