---
images:
- name: linuxserver/calibre
  newName: lscr.io/linuxserver/calibre
  newTag: version-v9.8.0@sha256:db4df4f7b40c39521c5607cff53184101dc25c17b570da2a41d69e104a2f1777
labels:
- pairs:
    "app.kubernetes.io/name": calibre
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- okinawa-media-books.yaml
