---
images:
- name: linuxserver/calibre
  newName: lscr.io/linuxserver/calibre
  newTag: version-v9.15.0@sha256:c97f86a5acc3372d5e25e75b4c98d1bffa64e70d4c413554beb1e554ae109187
labels:
- pairs:
    "app.kubernetes.io/name": calibre
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
- okinawa-media-books.yaml
