---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- openclaw-secrets.sealed.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
configMapGenerator:
- name: openclaw-config
  files:
  - openclaw.json=config/openclaw.json5
  - telegram-channel.json=config/telegram-channel.json5
  - AGENTS.md=config/AGENTS.md
commonLabels:
  app.kubernetes.io/name: openclaw
  app.kubernetes.io/instance: openclaw
images:
- name: ghcr.io/openclaw/openclaw
  newTag: 2026.4.14@sha256:7ea070b04d1e70811fe8ba15feaad5890b1646021b24e00f4795bd4587a594ed
