---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- openclaw-secrets.sealed.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
configMapGenerator:
- name: openclaw-config
  files:
  - openclaw.json=config/openclaw.json5
  - telegram-channel.json=config/telegram-channel.json5
  - AGENTS.md=config/AGENTS.md
commonLabels:
  app.kubernetes.io/name: openclaw
  app.kubernetes.io/instance: openclaw
images:
- name: ghcr.io/openclaw/openclaw
  newTag: 2026.5.27@sha256:555d6512c8adc145911c0f3d383663da2f7032d52547f7a1ee1da382a819d3bc
