---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- deployment.yaml
- service.yaml
- openclaw-secrets.sealed.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
configMapGenerator:
- name: openclaw-config
  files:
  - openclaw.json=config/openclaw.json5
  - AGENTS.md=config/AGENTS.md
commonLabels:
  app.kubernetes.io/name: openclaw
  app.kubernetes.io/instance: openclaw
