---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: ai-lab
spec:
  encryptedData:
    CLOUDFLARE_AI_GATEWAY_API_KEY: AgCLyqoAvFinn9F+ROQqP54OgoSjYm6wV+v59SHX5OF6E1vvhqf/QhbfQLp1hO3vTGKcyvUE/G8tOQNuGXqkvNW2xd2tckE4kSbE/SsiQbSyPYWxd/rlaH7nkCf6pJoXLFYm8m17pbX5fNWjspzmQsqkFN3xXeZT2DnYjbHKizuzmouDV37Gs6d5wdv07HNpA1z1/TlPE/fXCt/D1ak/7H09yVsfcKRp42c6dIb847FuzClDvv4/7buEBqqPgUZkMVeGgdjSkJor784wMELKZ8qrFCrt8MTWlGohXW5suLUZKJQiuZR/mt/BeuXA03oGmPW4iT8z43KCnn9c9Gf3AwZN1/ZtTbx4JcVitbaLCNTzVCjUPd7d/5k3Lp7+eCvWM/dNxQaKBMt+TVSh1DZXW4z4hGqOziR/96z+YuCbqcf7+M6Y2wPDqX60DhGQEQKhHi18xIImYX5aRjhnwYJVCao72dNpE82r6c7lIV9GdeeOmUW7NCZgQA3tDRh5aq7M0ItEgjrDmXpycUBaAYUgZB5kxI0th/VRJ4ADsACg4IHsxxvmAxWT+CxXl+hgnZYLNXEiaPMAaCDX7KBl4xcAkHxSTSasMgs3uRHar4K8u4NZoCYk7q1wM6HI7+8YZCpzxAuIMASCSBjqZ2I4/QtpB5BoE+FeJIuYDRWkF/q/oAlnzG3/7CXNkv7B51p2bq4t1ScSJPPOsSyXaxRmp6YMPCr8Q/9x6KfdxNwoeHi7e8m5phAUgEMOmP9SLE74IxIj8PLocIhMVA==
  template:
    metadata:
      name: openclaw-secrets
      namespace: ai-lab
    type: Opaque
