---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: ai-lab
spec:
  encryptedData:
    CLOUDFLARE_AI_GATEWAY_API_KEY: AgBZhldtyZz7xxvN42LyhuYAmHXr4LZcPdu9zdpFbQVWq09/czPvvAJm1yZ/DYT11hNFhgGAmDUSwosj7iH9aUYDIQgk+gyw7eNn+YWfw8cYEvnArGj+tiwsB5yZCa93OUt5RG1KHKjVS1uYF9tZCYP9JjykX9t9JBSnH5zW2OWwZD2G0VJNIjpNj4xgsQZ/ldNHjei4xT4dbT9+vtg7S8uHvbKorWmzix+vnG4zLKpTATpFLsVSnuZ8zWFLE8nlOTXgmeXBBpcU0l83h2X1vHO+jY/UrOiwfkhLgVmBA+R+A61lup9cfIgXWXFKawHRRJgvZ2BoV6EF5EByzkcf6l1jEym9JpxvAJrGWkp9Y0yEOuavr1Q+3k8SVoc18vXhkDZ3yE6fQKmKKnQ0c1tesYGGc+2ft9VxYYrxLZW8qhvJh4fyTmXNXj/2YSvo2pi0jC4Xa3LOam4VCcRBsPyBZOUi2rLawyeKs2Mpaa1IXT+nYH1/NAN4KbcOph8mnWM5XLZulz73Skvz7qAC5LYt0mJ8XyOUPr/zanvbTi7KnTjq0DKAfqVKj7HGWmON9CnMvRHdGET6KLlHQ9R4XZ+rwiU+8yLdAmOJ6WYm9veZHLL61EOSS+HZ7ZhR5TYD6IaUGnD8veoyHqLZf8ftlYlZ3ZPwJtIZkxBcKp0c3bnlELvJt+KAKRUEex3IcPPvV0rJQhMYKtMTf56sMnVjz0DMir1RP+82L/whPDnqDFW51CN7RIljQWmZWdXyHuXlJqaz4lIHO/LDaw==
    OPENROUTER_API_KEY: AgCjV1et90Hc8Azj4Yb9sk1icJVN9qBNbTNLAAXyb+Q4NjGte3ZUji4jcnYNQR8jnU0VZhKq0lH8EUhCxi1S16alwpAazup4ZPBE12qjzP3Nd7CmMoSC4Tms69kihZ2/AWLtpDA8kAore5glN0YPg94PGkqsB/SuHU6zPgMMNKr60p186OAwkYh7YWQ6kPLpQW4+kkoc1NLcHqbbCRCgxV8gd17DtCOWsnwlALaqg42KEsYP0I/hLw3nUahVNLj8bu3AjyMvNjHm/HcORAAu9TMUnL3TWuz1vDxlBowVua9milOCObXFGg0ReRAVyHl1dtKc0t9vjKbjzWY+HwOu0g/6NqfarvBUkHaOuC6g7wCd1fORuUpX8tPEo3+8y5Wokvr0QfDQexKVtnIz1pLp54OTgUs+vNntWvHq3BdrfT7VSqAiTXdqSv76cfhazidSlCoLoLiWYuDWx+0p4WvdIkrjInx2a0vi/PKNp4zWQap8HneEZ3gPDVtndYTcRgfTMopFUdoaUinde1FO6gAVgGVEPmiVs3YrIvWlLB+xCaZhX/D0UsbjcO6gGoLXGJARFmJGYFU+1xwHE+DMbCEoXC/dU9KV8UlGZ1WhX9+1hvXCbUbAYibH78EgjcMbUstBuOT+RD0pGJ5jgehTi02TLNm8hrC2hRPYjckPkaa+6nF2eB6L1HxTp9/VXUX8gIpgvy1rydebrr/id3ZjlLaKYM98TnsjyNI2m8qCYwZQGXMkuyLFKy6kyKIsHkQd2uzAEVDoWYRYC92GVVy4geYrqCu72X/IxPcLirC+
  template:
    metadata:
      name: openclaw-secrets
      namespace: ai-lab
    type: Opaque
