---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home-pvc
  labels:
    app: openclaw
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: okinawa-hdd-nfs
  resources:
    requests:
      storage: 10Gi
